// 자동 생성 — 학습앱을 하나씩 참조한 밝은 테마 21종.
// 색만이 아니라 화면 구조(structure)·서체·여백·형태가 함께 바뀐다.
// 대비와 밝기는 생성 시점에 수치로 검증·보정된다.
import type { Theme } from './themeTypes';

export const THEMES: Theme[] = [
  {
    "id": "duolingo",
    "name": "새싹 초록",
    "nameEn": "Sprout Green",
    "reference": "듀오링고 — 채도 높은 한 색을 버튼에만 크게 쓰고 지면은 비운다. 굵고 둥근 서체, 아래로 두꺼운 그림자가 깔린 3D 버튼.",
    "idea": "초록은 오직 눌러야 할 것에만 쓰고, 나머지는 흰 종이로 비워 둔다.",
    "colors": {
      "canvas": "#FFFFFF",
      "surface": "#FFFFFF",
      "ink": "#17281B",
      "textSecondary": "#3C5541",
      "muted": "#5A7360",
      "line": "#d0e0d2",
      "primary": "#4FB81E",
      "primaryDark": "#2F7A0F",
      "primarySoft": "#E4F7D6",
      "accent": "#F5A623",
      "onPrimary": "#17281B",
      "success": "#3A9A2B",
      "warning": "#C97A0A",
      "danger": "#D8453C",
      "backdrop": "#f7f6f6",
      "accentSoft": "#f4eeda",
      "successSoft": "#e7f0e3",
      "warningSoft": "#f6f0e1",
      "dangerSoft": "#f1e0e2"
    },
    "type": {
      "display": "Jua",
      "body": "Gothic A1",
      "displayWeight": 400,
      "bodyWeight": 500,
      "displaySize": 34,
      "bodySize": 15,
      "displayTracking": -0.6,
      "displayLine": 1.22,
      "bodyLine": 1.55,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "focus-list",
      "header": "stacked",
      "list": "card",
      "button": "block",
      "progress": "bar",
      "photo": "rounded",
      "density": "open",
      "radius": 16,
      "hairline": 2,
      "shadow": "none",
      "edge": 22
    },
    "photo": {
      "heroTags": "vietnam,daylight",
      "lock": 11
    },
    "avoid": "초록을 배경이나 테두리에 번지게 쓰지 않는다. 버튼과 진도바에만.",
    "rationale": "듀오링고 — 채도 높은 한 색을 버튼에만 크게 쓰고 지면은 비운다. 굵고 둥근 서체, 아래로 두꺼운 그림자가 깔린 3D 버튼."
  },
  {
    "id": "khan-academy",
    "name": "교실 초록",
    "nameEn": "Classroom Teal",
    "reference": "칸아카데미 — 교육기관의 차분함. 장식 없이 구분선으로 정리하고 진도를 중심에 둔다.",
    "idea": "가르치는 사람의 화면. 색은 진도에만 쓰고 나머지는 글자와 선으로 정리한다.",
    "colors": {
      "canvas": "#F7FBFA",
      "surface": "#FFFFFF",
      "ink": "#14312C",
      "textSecondary": "#3D5F58",
      "muted": "#5C7C76",
      "line": "#b6d2cd",
      "primary": "#2b8373",
      "primaryDark": "#1B5F52",
      "primarySoft": "#DAF0EB",
      "accent": "#C4622A",
      "onPrimary": "#ffffff",
      "success": "#2E8B5E",
      "warning": "#B0740F",
      "danger": "#C4453F",
      "backdrop": "#e9f7f2",
      "accentSoft": "#f0e7de",
      "successSoft": "#e4efe7",
      "warningSoft": "#f6f1e2",
      "dangerSoft": "#efe2e3"
    },
    "type": {
      "display": "Noto Sans KR",
      "body": "Noto Sans KR",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 30,
      "bodySize": 15,
      "displayTracking": -0.4,
      "displayLine": 1.28,
      "bodyLine": 1.62,
      "labelTracking": 0.6,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "plain-list",
      "header": "editorial",
      "list": "rule",
      "button": "rect",
      "progress": "rule",
      "photo": "square",
      "density": "normal",
      "radius": 4,
      "hairline": 1,
      "shadow": "none",
      "edge": 22
    },
    "photo": {
      "heroTags": "classroom,daylight",
      "lock": 23
    },
    "avoid": "카드와 그림자를 쓰지 않는다. 구분선과 여백으로만 나눈다.",
    "rationale": "칸아카데미 — 교육기관의 차분함. 장식 없이 구분선으로 정리하고 진도를 중심에 둔다."
  },
  {
    "id": "quizlet",
    "name": "인디고 카드",
    "nameEn": "Indigo Cards",
    "reference": "퀴즐렛 — 흰 지면 위 플래시카드. 한 화면에 많은 항목을 담는 밀도.",
    "idea": "카드 격자로 한눈에 훑는다. 정보 밀도를 위해 여백을 줄이되 카드는 또렷하게.",
    "colors": {
      "canvas": "#FAFAFF",
      "surface": "#FFFFFF",
      "ink": "#1B1F3B",
      "textSecondary": "#41476E",
      "muted": "#5F6690",
      "line": "#D8DAEC",
      "primary": "#6272E8",
      "primaryDark": "#3A46AE",
      "primarySoft": "#E3E5FA",
      "accent": "#18B39B",
      "onPrimary": "#080d35",
      "success": "#1E8F72",
      "warning": "#B07A12",
      "danger": "#CE4059",
      "backdrop": "#e4e7ff",
      "accentSoft": "#dcf2f1",
      "successSoft": "#e2f1ea",
      "warningSoft": "#f5f1e3",
      "dangerSoft": "#f0e1e6"
    },
    "type": {
      "display": "Pretendard",
      "body": "Pretendard",
      "displayWeight": 800,
      "bodyWeight": 500,
      "displaySize": 30,
      "bodySize": 14,
      "displayTracking": -0.7,
      "displayLine": 1.2,
      "bodyLine": 1.5,
      "labelTracking": 0.5,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "grid",
      "header": "compact",
      "list": "card",
      "button": "rect",
      "progress": "count",
      "photo": "square",
      "density": "tight",
      "radius": 8,
      "hairline": 1,
      "shadow": "hair",
      "edge": 18
    },
    "photo": {
      "heroTags": "library,daylight",
      "lock": 37
    },
    "avoid": "장식적인 일러스트를 넣지 않는다. 카드와 글자만.",
    "rationale": "퀴즐렛 — 흰 지면 위 플래시카드. 한 화면에 많은 항목을 담는 밀도."
  },
  {
    "id": "coursera",
    "name": "강의실 파랑",
    "nameEn": "Lecture Blue",
    "reference": "코세라 — 대학 강의 플랫폼의 단정한 기업형 톤. 구분선과 여백으로 정리하고 파랑 하나.",
    "idea": "수강 목록을 읽는 화면. 꾸미지 않고, 읽는 순서만 분명하게.",
    "colors": {
      "canvas": "#F6F9FE",
      "surface": "#FFFFFF",
      "ink": "#16233A",
      "textSecondary": "#3E4E6B",
      "muted": "#5D6C88",
      "line": "#becbe0",
      "primary": "#2668D8",
      "primaryDark": "#17479C",
      "primarySoft": "#DCE7FA",
      "accent": "#D2762A",
      "onPrimary": "#FFFFFF",
      "success": "#217A5C",
      "warning": "#AA7014",
      "danger": "#C24438",
      "backdrop": "#e2f0ff",
      "accentSoft": "#f0e9dd",
      "successSoft": "#e3f0e9",
      "warningSoft": "#f5f0e3",
      "dangerSoft": "#efe2e3"
    },
    "type": {
      "display": "Pretendard",
      "body": "Noto Sans KR",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 15,
      "displayTracking": -0.5,
      "displayLine": 1.26,
      "bodyLine": 1.62,
      "labelTracking": 0.7,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "plain-list",
      "header": "rule",
      "list": "rule",
      "button": "rect",
      "progress": "bar",
      "photo": "square",
      "density": "normal",
      "radius": 4,
      "hairline": 1,
      "shadow": "none",
      "edge": 22
    },
    "photo": {
      "heroTags": "university,daylight",
      "lock": 41
    },
    "avoid": "둥근 카드와 그림자를 쓰지 않는다.",
    "rationale": "코세라 — 대학 강의 플랫폼의 단정한 기업형 톤. 구분선과 여백으로 정리하고 파랑 하나."
  },
  {
    "id": "udemy",
    "name": "보라 카탈로그",
    "nameEn": "Violet Catalog",
    "reference": "유데미 — 강의 카탈로그. 썸네일 사진이 크고 그 아래 정보가 붙는다.",
    "idea": "사진이 먼저 말하고 글자가 뒤따른다. 상단에 큰 실사 한 장.",
    "colors": {
      "canvas": "#FBF9FF",
      "surface": "#FFFFFF",
      "ink": "#241A3A",
      "textSecondary": "#4B3F6B",
      "muted": "#68598B",
      "line": "#DCD5EC",
      "primary": "#7B4BD8",
      "primaryDark": "#52299E",
      "primarySoft": "#EBE2FB",
      "accent": "#E0913A",
      "onPrimary": "#FFFFFF",
      "success": "#2C8460",
      "warning": "#B57A16",
      "danger": "#CB4356",
      "backdrop": "#eae3ff",
      "accentSoft": "#f1eadd",
      "successSoft": "#e4efe8",
      "warningSoft": "#f5f1e3",
      "dangerSoft": "#f0e2e6"
    },
    "type": {
      "display": "Gothic A1",
      "body": "Gothic A1",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 30,
      "bodySize": 14.5,
      "displayTracking": -0.6,
      "displayLine": 1.24,
      "bodyLine": 1.58,
      "labelTracking": 0.6,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "hero-list",
      "header": "photo",
      "list": "card",
      "button": "rect",
      "progress": "bar",
      "photo": "wide",
      "density": "normal",
      "radius": 10,
      "hairline": 1,
      "shadow": "hair",
      "edge": 20
    },
    "photo": {
      "heroTags": "seoul,street,daylight",
      "lock": 53
    },
    "avoid": "사진 위에 색면을 덧대지 않는다. 스크림만.",
    "rationale": "유데미 — 강의 카탈로그. 썸네일 사진이 크고 그 아래 정보가 붙는다."
  },
  {
    "id": "babbel",
    "name": "따뜻한 주황",
    "nameEn": "Warm Amber",
    "reference": "바벨 — 성인 학습자를 위한 차분한 톤. 장식을 줄이고 텍스트 위계로 정리한다.",
    "idea": "어른이 쓰는 학습앱. 들뜨지 않게, 주황은 한 번만.",
    "colors": {
      "canvas": "#FFFBF7",
      "surface": "#FFFFFF",
      "ink": "#33210F",
      "textSecondary": "#5E4527",
      "muted": "#7B613F",
      "line": "#dec9b2",
      "primary": "#EE7B2C",
      "primaryDark": "#A44B08",
      "primarySoft": "#FCE6D2",
      "accent": "#3E7FB8",
      "onPrimary": "#3A1D06",
      "success": "#2F7F58",
      "warning": "#9C6A0E",
      "danger": "#C0402F",
      "backdrop": "#ffefe1",
      "accentSoft": "#e0e5ee",
      "successSoft": "#e4efe8",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#f0e1e2"
    },
    "type": {
      "display": "Pretendard",
      "body": "Pretendard",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 30,
      "bodySize": 15,
      "displayTracking": -0.5,
      "displayLine": 1.26,
      "bodyLine": 1.6,
      "labelTracking": 0.5,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "plain-list",
      "header": "editorial",
      "list": "rule",
      "button": "outline",
      "progress": "count",
      "photo": "square",
      "density": "normal",
      "radius": 8,
      "hairline": 1,
      "shadow": "none",
      "edge": 24
    },
    "photo": {
      "heroTags": "cafe,daylight",
      "lock": 67
    },
    "avoid": "주황을 배경 면으로 깔지 않는다.",
    "rationale": "바벨 — 성인 학습자를 위한 차분한 톤. 장식을 줄이고 텍스트 위계로 정리한다."
  },
  {
    "id": "memrise",
    "name": "민트 팝",
    "nameEn": "Mint Pop",
    "reference": "멤라이즈 — 선명한 색과 팝한 인터랙션. 놀이하듯 가벼운 톤, 큼직한 둥근 형태.",
    "idea": "가볍게 넘기며 외우는 화면. 둥글고 크게, 격자로.",
    "colors": {
      "canvas": "#F5FDFB",
      "surface": "#FFFFFF",
      "ink": "#0F2E2A",
      "textSecondary": "#2F5D56",
      "muted": "#4C7B73",
      "line": "#bbe5dc",
      "primary": "#17BFA6",
      "primaryDark": "#0A7E6C",
      "primarySoft": "#D6F7EF",
      "accent": "#F2683E",
      "onPrimary": "#06302A",
      "success": "#189A6E",
      "warning": "#B3760C",
      "danger": "#D14A45",
      "backdrop": "#e3fef4",
      "accentSoft": "#f3e4da",
      "successSoft": "#e1f2e9",
      "warningSoft": "#f6f1e2",
      "dangerSoft": "#f0e1e3"
    },
    "type": {
      "display": "Do Hyeon",
      "body": "Gothic A1",
      "displayWeight": 400,
      "bodyWeight": 500,
      "displaySize": 32,
      "bodySize": 15,
      "displayTracking": -0.4,
      "displayLine": 1.2,
      "bodyLine": 1.55,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "grid",
      "header": "stacked",
      "list": "card",
      "button": "pill",
      "progress": "dots",
      "photo": "circle",
      "density": "normal",
      "radius": 20,
      "hairline": 1,
      "shadow": "soft",
      "edge": 20
    },
    "photo": {
      "heroTags": "market,daylight",
      "lock": 79
    },
    "avoid": "각진 모서리와 얇은 글자를 쓰지 않는다.",
    "rationale": "멤라이즈 — 선명한 색과 팝한 인터랙션. 놀이하듯 가벼운 톤, 큼직한 둥근 형태."
  },
  {
    "id": "busuu",
    "name": "맑은 하늘 코스",
    "nameEn": "Clear Sky Course",
    "reference": "부수 — 커리큘럼과 진도가 또렷한 정돈된 구조. 카드보다 테두리로 구획한다.",
    "idea": "배울 순서를 먼저 보여준다. 분류 탭으로 나누고 테두리로 묶는다.",
    "colors": {
      "canvas": "#F5FBFF",
      "surface": "#FFFFFF",
      "ink": "#10293A",
      "textSecondary": "#365468",
      "muted": "#537285",
      "line": "#C6DEEC",
      "primary": "#2C9BE0",
      "primaryDark": "#125F94",
      "primarySoft": "#DAF0FC",
      "accent": "#E8973C",
      "onPrimary": "#082435",
      "success": "#20876A",
      "warning": "#A8720F",
      "danger": "#C6474A",
      "backdrop": "#def9ff",
      "accentSoft": "#f2ebdc",
      "successSoft": "#e2f0ea",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#efe2e4"
    },
    "type": {
      "display": "Gothic A1",
      "body": "Gothic A1",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 14.5,
      "displayTracking": -0.5,
      "displayLine": 1.24,
      "bodyLine": 1.58,
      "labelTracking": 0.8,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "tabs-list",
      "header": "compact",
      "list": "outline",
      "button": "rect",
      "progress": "bar",
      "photo": "rounded",
      "density": "normal",
      "radius": 10,
      "hairline": 1,
      "shadow": "none",
      "edge": 20
    },
    "photo": {
      "heroTags": "seoul,daylight",
      "lock": 83
    },
    "avoid": "그림자를 쓰지 않는다. 테두리로만 나눈다.",
    "rationale": "부수 — 커리큘럼과 진도가 또렷한 정돈된 구조. 카드보다 테두리로 구획한다."
  },
  {
    "id": "photomath",
    "name": "라임 풀이",
    "nameEn": "Lime Solver",
    "reference": "포토매스 — 문제를 스캔하고 풀이 단계를 보여준다. 숫자와 단계가 화면의 주인공.",
    "idea": "지금 몇 개 중 몇 번째인지, 숫자를 화면 맨 위에 크게 세운다.",
    "colors": {
      "canvas": "#FAFDF6",
      "surface": "#FFFFFF",
      "ink": "#1D2A14",
      "textSecondary": "#41552F",
      "muted": "#5F754C",
      "line": "#d0e2be",
      "primary": "#6FC72E",
      "primaryDark": "#3F7D12",
      "primarySoft": "#E9F8D6",
      "accent": "#3F76C8",
      "onPrimary": "#152207",
      "success": "#2F8A46",
      "warning": "#A87A0C",
      "danger": "#C6474A",
      "backdrop": "#f5fde4",
      "accentSoft": "#dfe3ef",
      "successSoft": "#e4efe5",
      "warningSoft": "#f6f3e2",
      "dangerSoft": "#efe2e4"
    },
    "type": {
      "display": "IBM Plex Sans KR",
      "body": "IBM Plex Sans KR",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 30,
      "bodySize": 14,
      "displayTracking": -0.4,
      "displayLine": 1.22,
      "bodyLine": 1.55,
      "labelTracking": 0.9,
      "labelCase": "upper"
    },
    "layout": {
      "structure": "stat-list",
      "header": "compact",
      "list": "inset",
      "button": "pill",
      "progress": "count",
      "photo": "square",
      "density": "tight",
      "radius": 12,
      "hairline": 1,
      "shadow": "none",
      "edge": 18
    },
    "photo": {
      "heroTags": "notebook,daylight",
      "lock": 97
    },
    "avoid": "사진을 크게 쓰지 않는다. 숫자가 주인공이다.",
    "rationale": "포토매스 — 문제를 스캔하고 풀이 단계를 보여준다. 숫자와 단계가 화면의 주인공."
  },
  {
    "id": "brilliant",
    "name": "코발트 도식",
    "nameEn": "Cobalt Diagram",
    "reference": "브릴리언트 — 인터랙티브 문제 풀이. 도식과 선이 많고 테두리로 영역을 나눈다.",
    "idea": "선으로 그린 화면. 면을 만들지 않고 테두리와 숫자로만 구조를 세운다.",
    "colors": {
      "canvas": "#F8FAFF",
      "surface": "#FFFFFF",
      "ink": "#18213B",
      "textSecondary": "#3E4A6D",
      "muted": "#5C688C",
      "line": "#c1cae4",
      "primary": "#3B6FE8",
      "primaryDark": "#1E47AE",
      "primarySoft": "#DEE7FC",
      "accent": "#E88A2C",
      "onPrimary": "#FFFFFF",
      "success": "#1F8365",
      "warning": "#AC7411",
      "danger": "#C34756",
      "backdrop": "#e2efff",
      "accentSoft": "#f2eadb",
      "successSoft": "#e2f0ea",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#efe2e6"
    },
    "type": {
      "display": "IBM Plex Sans KR",
      "body": "IBM Plex Sans KR",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 13.5,
      "displayTracking": -0.3,
      "displayLine": 1.24,
      "bodyLine": 1.6,
      "labelTracking": 1.2,
      "labelCase": "upper"
    },
    "layout": {
      "structure": "stat-list",
      "header": "rule",
      "list": "outline",
      "button": "rect",
      "progress": "count",
      "photo": "square",
      "density": "tight",
      "radius": 6,
      "hairline": 1,
      "shadow": "none",
      "edge": 18
    },
    "photo": {
      "heroTags": "geometry,daylight",
      "lock": 101
    },
    "avoid": "그림자와 채워진 카드를 쓰지 않는다.",
    "rationale": "브릴리언트 — 인터랙티브 문제 풀이. 도식과 선이 많고 테두리로 영역을 나눈다."
  },
  {
    "id": "elsa-speak",
    "name": "보라 발음",
    "nameEn": "Violet Speech",
    "reference": "엘사 스피크 — 발음 점수가 화면의 주인공. 점수를 크게, 나머지는 부드럽게.",
    "idea": "지금 연습하는 한 단어를 크게 세우고, 점수와 파형이 그 곁에 붙는다.",
    "colors": {
      "canvas": "#FDF8FF",
      "surface": "#FFFFFF",
      "ink": "#2B1738",
      "textSecondary": "#523362",
      "muted": "#6E4C7E",
      "line": "#E2D2EC",
      "primary": "#A34BD6",
      "primaryDark": "#6B2497",
      "primarySoft": "#F2E2FB",
      "accent": "#2FA6A0",
      "onPrimary": "#FFFFFF",
      "success": "#25876F",
      "warning": "#A6720F",
      "danger": "#C2465E",
      "backdrop": "#f6e2ff",
      "accentSoft": "#dfedef",
      "successSoft": "#e3f0ea",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#efe2e7"
    },
    "type": {
      "display": "Pretendard",
      "body": "Gothic A1",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 31,
      "bodySize": 14.5,
      "displayTracking": -0.7,
      "displayLine": 1.2,
      "bodyLine": 1.55,
      "labelTracking": 0.5,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "focus-list",
      "header": "stacked",
      "list": "card",
      "button": "pill",
      "progress": "dots",
      "photo": "circle",
      "density": "normal",
      "radius": 18,
      "hairline": 1,
      "shadow": "soft",
      "edge": 20
    },
    "photo": {
      "heroTags": "microphone,daylight",
      "lock": 113
    },
    "avoid": "보라를 넓은 면으로 깔지 않는다. 지면은 거의 흰색으로.",
    "rationale": "엘사 스피크 — 발음 점수가 화면의 주인공. 점수를 크게, 나머지는 부드럽게."
  },
  {
    "id": "hellotalk",
    "name": "대화 하늘",
    "nameEn": "Talk Sky",
    "reference": "헬로톡 — 사람과 대화하는 앱. 프로필 원형 사진과 말풍선 같은 부드러운 덩어리.",
    "idea": "사람 얼굴이 먼저 보이는 화면. 원형 사진과 둥근 덩어리로 대화의 결을 만든다.",
    "colors": {
      "canvas": "#F6FBFF",
      "surface": "#FFFFFF",
      "ink": "#12293B",
      "textSecondary": "#365468",
      "muted": "#547287",
      "line": "#C8DFEE",
      "primary": "#2FA8E8",
      "primaryDark": "#12689E",
      "primarySoft": "#DBF0FD",
      "accent": "#F07C58",
      "onPrimary": "#062637",
      "success": "#238A6C",
      "warning": "#A9750E",
      "danger": "#C64B4B",
      "backdrop": "#dff7ff",
      "accentSoft": "#f3e4db",
      "successSoft": "#e3f0ea",
      "warningSoft": "#f6f2e2",
      "dangerSoft": "#efe2e4"
    },
    "type": {
      "display": "Gowun Dodum",
      "body": "Pretendard",
      "displayWeight": 400,
      "bodyWeight": 400,
      "displaySize": 30,
      "bodySize": 15,
      "displayTracking": -0.3,
      "displayLine": 1.26,
      "bodyLine": 1.62,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "hero-list",
      "header": "photo",
      "list": "card",
      "button": "pill",
      "progress": "count",
      "photo": "circle",
      "density": "normal",
      "radius": 14,
      "hairline": 1,
      "shadow": "hair",
      "edge": 20
    },
    "photo": {
      "heroTags": "people,street,daylight",
      "lock": 127
    },
    "avoid": "각진 모서리를 쓰지 않는다.",
    "rationale": "헬로톡 — 사람과 대화하는 앱. 프로필 원형 사진과 말풍선 같은 부드러운 덩어리."
  },
  {
    "id": "drops",
    "name": "다섯 시 산호",
    "nameEn": "Five Minute Coral",
    "reference": "드롭스 — 텍스트를 극단적으로 줄이고 큰 그래픽 하나로 화면을 채운다. 5분 학습.",
    "idea": "한 화면에 한 단어. 사진을 크게 두고 글자는 최소로 줄인다.",
    "colors": {
      "canvas": "#FFFFFF",
      "surface": "#FFFFFF",
      "ink": "#2A1512",
      "textSecondary": "#563029",
      "muted": "#734A42",
      "line": "#dfc7c1",
      "primary": "#F0574F",
      "primaryDark": "#B02A22",
      "primarySoft": "#FCE0DC",
      "accent": "#2E9AA8",
      "onPrimary": "#380705",
      "success": "#2A8A63",
      "warning": "#AA7212",
      "danger": "#C0392E",
      "backdrop": "#f7f6f6",
      "accentSoft": "#dfebef",
      "successSoft": "#e3efe8",
      "warningSoft": "#f5f1e3",
      "dangerSoft": "#f0e1e2"
    },
    "type": {
      "display": "Black Han Sans",
      "body": "Gothic A1",
      "displayWeight": 400,
      "bodyWeight": 400,
      "displaySize": 40,
      "bodySize": 15,
      "displayTracking": -1.2,
      "displayLine": 1.1,
      "bodyLine": 1.6,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "focus-list",
      "header": "photo",
      "list": "rule",
      "button": "text",
      "progress": "none",
      "photo": "wide",
      "density": "open",
      "radius": 0,
      "hairline": 1,
      "shadow": "none",
      "edge": 24
    },
    "photo": {
      "heroTags": "vietnam,street,daylight",
      "lock": 131
    },
    "avoid": "진행 표시를 넣지 않는다. 화면에 요소를 더하지 않는다.",
    "rationale": "드롭스 — 텍스트를 극단적으로 줄이고 큰 그래픽 하나로 화면을 채운다. 5분 학습."
  },
  {
    "id": "lingodeer",
    "name": "문법 파랑",
    "nameEn": "Grammar Blue",
    "reference": "링고디어 — 아시아 언어 문법 설명이 많아 정보가 빽빽하다. 배경 톤 블록으로 문단을 구분한다.",
    "idea": "설명이 많은 화면. 배경 톤으로 덩어리를 나눠 읽는 부담을 줄인다.",
    "colors": {
      "canvas": "#F7FAFF",
      "surface": "#FFFFFF",
      "ink": "#16223C",
      "textSecondary": "#3B4A6B",
      "muted": "#59688A",
      "line": "#D2DAEC",
      "primary": "#477de9",
      "primaryDark": "#1F4CA8",
      "primarySoft": "#E0E9FC",
      "accent": "#F0B429",
      "onPrimary": "#071737",
      "success": "#22815F",
      "warning": "#A87313",
      "danger": "#C24552",
      "backdrop": "#e1f1ff",
      "accentSoft": "#f3efdb",
      "successSoft": "#e3f0e9",
      "warningSoft": "#f5f1e3",
      "dangerSoft": "#efe2e5"
    },
    "type": {
      "display": "Gothic A1",
      "body": "Noto Sans KR",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 28,
      "bodySize": 14,
      "displayTracking": -0.4,
      "displayLine": 1.24,
      "bodyLine": 1.62,
      "labelTracking": 0.7,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "tabs-list",
      "header": "compact",
      "list": "inset",
      "button": "rect",
      "progress": "bar",
      "photo": "square",
      "density": "tight",
      "radius": 12,
      "hairline": 1,
      "shadow": "none",
      "edge": 18
    },
    "photo": {
      "heroTags": "hanok,daylight",
      "lock": 149
    },
    "avoid": "테두리를 쓰지 않는다. 배경 톤으로만 구분한다.",
    "rationale": "링고디어 — 아시아 언어 문법 설명이 많아 정보가 빽빽하다. 배경 톤 블록으로 문단을 구분한다."
  },
  {
    "id": "rosetta",
    "name": "황금 사진",
    "nameEn": "Golden Photo",
    "reference": "로제타스톤 — 사진으로 뜻을 익힌다. 사진이 크고 텍스트는 짧다.",
    "idea": "번역 대신 사진으로 뜻을 붙인다. 사진이 가장 큰 요소.",
    "colors": {
      "canvas": "#FFFCF3",
      "surface": "#FFFFFF",
      "ink": "#2E2410",
      "textSecondary": "#584626",
      "muted": "#77633E",
      "line": "#E6D7B8",
      "primary": "#D69A18",
      "primaryDark": "#8A5D06",
      "primarySoft": "#FBEECD",
      "accent": "#3B72A8",
      "onPrimary": "#2A1F06",
      "success": "#2F8154",
      "warning": "#A06A0C",
      "danger": "#BF4132",
      "backdrop": "#fff6dc",
      "accentSoft": "#e0e5ee",
      "successSoft": "#e4efe7",
      "warningSoft": "#f6f1e2",
      "dangerSoft": "#f0e1e2"
    },
    "type": {
      "display": "Gothic A1",
      "body": "Gothic A1",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 15,
      "displayTracking": -0.4,
      "displayLine": 1.26,
      "bodyLine": 1.6,
      "labelTracking": 0.6,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "hero-list",
      "header": "photo",
      "list": "card",
      "button": "rect",
      "progress": "bar",
      "photo": "wide",
      "density": "normal",
      "radius": 10,
      "hairline": 1,
      "shadow": "hair",
      "edge": 20
    },
    "photo": {
      "heroTags": "nature,daylight",
      "lock": 151
    },
    "avoid": "설명 문장을 길게 쓰지 않는다.",
    "rationale": "로제타스톤 — 사진으로 뜻을 익힌다. 사진이 크고 텍스트는 짧다."
  },
  {
    "id": "italki",
    "name": "튜터 레드",
    "nameEn": "Tutor Red",
    "reference": "아이토키 — 튜터 프로필이 중심. 원형 사진과 이름이 한 줄에 붙는다.",
    "idea": "사람을 고르는 화면의 문법을 단어 고르기에 옮긴다. 원형 사진 격자.",
    "colors": {
      "canvas": "#FFF9F8",
      "surface": "#FFFFFF",
      "ink": "#33191A",
      "textSecondary": "#5E3230",
      "muted": "#7C4A46",
      "line": "#EBD1CD",
      "primary": "#e35443",
      "primaryDark": "#9E2A1E",
      "primarySoft": "#FBDED8",
      "accent": "#2F86A8",
      "onPrimary": "#350d08",
      "success": "#2B8060",
      "warning": "#A56E10",
      "danger": "#B93B36",
      "backdrop": "#ffe3e2",
      "accentSoft": "#dfe8ef",
      "successSoft": "#e4efe9",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#efe2e3"
    },
    "type": {
      "display": "Gothic A1",
      "body": "Pretendard",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 14,
      "displayTracking": -0.5,
      "displayLine": 1.22,
      "bodyLine": 1.55,
      "labelTracking": 0.5,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "grid",
      "header": "stacked",
      "list": "card",
      "button": "pill",
      "progress": "count",
      "photo": "circle",
      "density": "tight",
      "radius": 12,
      "hairline": 1,
      "shadow": "hair",
      "edge": 18
    },
    "photo": {
      "heroTags": "teacher,daylight",
      "lock": 163
    },
    "avoid": "빨강을 넓은 면으로 깔지 않는다.",
    "rationale": "아이토키 — 튜터 프로필이 중심. 원형 사진과 이름이 한 줄에 붙는다."
  },
  {
    "id": "anki",
    "name": "담백한 카드",
    "nameEn": "Plain Deck",
    "reference": "앙키 — 기능 우선. 장식이 전혀 없다. 얇은 테두리와 기본 목록.",
    "idea": "꾸미지 않는다. 필요한 것만 있고, 그것이 정확히 보인다.",
    "colors": {
      "canvas": "#FFFFFF",
      "surface": "#FFFFFF",
      "ink": "#1C2430",
      "textSecondary": "#3F4A59",
      "muted": "#5C6675",
      "line": "#c4cbd4",
      "primary": "#3A6EA5",
      "primaryDark": "#1F4571",
      "primarySoft": "#DEE8F2",
      "accent": "#A8582C",
      "onPrimary": "#FFFFFF",
      "success": "#2A7A57",
      "warning": "#96690F",
      "danger": "#B24138",
      "backdrop": "#f7f6f6",
      "accentSoft": "#efe7df",
      "successSoft": "#e4efe8",
      "warningSoft": "#f5f2e2",
      "dangerSoft": "#efe2e3"
    },
    "type": {
      "display": "Nanum Gothic Coding",
      "body": "Pretendard",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 27,
      "bodySize": 13.5,
      "displayTracking": 0,
      "displayLine": 1.24,
      "bodyLine": 1.6,
      "labelTracking": 1,
      "labelCase": "upper"
    },
    "layout": {
      "structure": "plain-list",
      "header": "rule",
      "list": "outline",
      "button": "rect",
      "progress": "count",
      "photo": "square",
      "density": "tight",
      "radius": 2,
      "hairline": 1,
      "shadow": "none",
      "edge": 16
    },
    "photo": {
      "heroTags": "desk,daylight",
      "lock": 167
    },
    "avoid": "색면·그림자·둥근 모서리를 쓰지 않는다.",
    "rationale": "앙키 — 기능 우선. 장식이 전혀 없다. 얇은 테두리와 기본 목록."
  },
  {
    "id": "cake",
    "name": "노랑 자막",
    "nameEn": "Yellow Caption",
    "reference": "케이크 — 노랑과 검정의 강한 대비. 영상 중심, 한국 앱 특유의 조밀한 정보.",
    "idea": "노랑 위에 검정. 자막처럼 굵고 짧게 끊어 읽힌다.",
    "colors": {
      "canvas": "#FFFEF5",
      "surface": "#FFFFFF",
      "ink": "#17150A",
      "textSecondary": "#443E22",
      "muted": "#635B34",
      "line": "#E0D9A8",
      "primary": "#FFD400",
      "primaryDark": "#8A7000",
      "primarySoft": "#FFF6C2",
      "accent": "#2B6BE0",
      "onPrimary": "#17150A",
      "success": "#2B7A4A",
      "warning": "#96690A",
      "danger": "#C33A2E",
      "backdrop": "#fffcde",
      "accentSoft": "#dce1f1",
      "successSoft": "#e4efe6",
      "warningSoft": "#f6f2e2",
      "dangerSoft": "#f0e1e2"
    },
    "type": {
      "display": "Black Han Sans",
      "body": "Pretendard",
      "displayWeight": 400,
      "bodyWeight": 500,
      "displaySize": 32,
      "bodySize": 14,
      "displayTracking": -0.8,
      "displayLine": 1.16,
      "bodyLine": 1.55,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "tabs-list",
      "header": "band",
      "list": "block",
      "button": "rect",
      "progress": "count",
      "photo": "wide",
      "density": "tight",
      "radius": 6,
      "hairline": 1.5,
      "shadow": "none",
      "edge": 18
    },
    "photo": {
      "heroTags": "street,food,daylight",
      "lock": 173
    },
    "avoid": "노랑 위에 흰 글자를 쓰지 않는다. 반드시 검정.",
    "rationale": "케이크 — 노랑과 검정의 강한 대비. 영상 중심, 한국 앱 특유의 조밀한 정보."
  },
  {
    "id": "speak",
    "name": "흰 종이 한 점",
    "nameEn": "One Blue Dot",
    "reference": "스픽 — 검정·흰색 미니멀. 말하기 하나에 집중하고 색은 한 점만.",
    "idea": "화면에서 색을 지운다. 파랑은 지금 눌러야 할 곳 한 군데에만 남긴다.",
    "colors": {
      "canvas": "#FFFFFF",
      "surface": "#FFFFFF",
      "ink": "#101215",
      "textSecondary": "#3A3F47",
      "muted": "#585F69",
      "line": "#c6cbd2",
      "primary": "#1F5EFF",
      "primaryDark": "#0B3AAE",
      "primarySoft": "#E2EAFF",
      "accent": "#111317",
      "onPrimary": "#FFFFFF",
      "success": "#20744F",
      "warning": "#8A6410",
      "danger": "#B2382F",
      "backdrop": "#f7f6f6",
      "accentSoft": "#e5e5e9",
      "successSoft": "#e3f0e8",
      "warningSoft": "#f5f2e3",
      "dangerSoft": "#f0e1e3"
    },
    "type": {
      "display": "Pretendard",
      "body": "Pretendard",
      "displayWeight": 800,
      "bodyWeight": 400,
      "displaySize": 32,
      "bodySize": 15,
      "displayTracking": -0.9,
      "displayLine": 1.2,
      "bodyLine": 1.6,
      "labelTracking": 0.6,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "focus-list",
      "header": "editorial",
      "list": "rule",
      "button": "rect",
      "progress": "count",
      "photo": "square",
      "density": "normal",
      "radius": 0,
      "hairline": 1,
      "shadow": "none",
      "edge": 24
    },
    "photo": {
      "heroTags": "microphone,studio,daylight",
      "lock": 179
    },
    "avoid": "두 번째 색을 쓰지 않는다.",
    "rationale": "스픽 — 검정·흰색 미니멀. 말하기 하나에 집중하고 색은 한 점만."
  },
  {
    "id": "santa",
    "name": "진단 보라",
    "nameEn": "Diagnostic Violet",
    "reference": "산타 — 점수와 진단 데이터가 화면의 주인공. 숫자가 크고 나머지는 조밀하다.",
    "idea": "맞힌 개수와 남은 개수를 맨 위에 숫자로 박아 둔다.",
    "colors": {
      "canvas": "#F8F8FF",
      "surface": "#FFFFFF",
      "ink": "#1A1A33",
      "textSecondary": "#3F3F63",
      "muted": "#5D5D85",
      "line": "#D5D5E8",
      "primary": "#5B4BE8",
      "primaryDark": "#3325AE",
      "primarySoft": "#E4E1FB",
      "accent": "#22A08A",
      "onPrimary": "#FFFFFF",
      "success": "#1F8A6E",
      "warning": "#A2700F",
      "danger": "#C2405A",
      "backdrop": "#e2e5ff",
      "accentSoft": "#def0ef",
      "successSoft": "#e2f0ea",
      "warningSoft": "#f5f1e2",
      "dangerSoft": "#efe2e7"
    },
    "type": {
      "display": "IBM Plex Sans KR",
      "body": "Pretendard",
      "displayWeight": 700,
      "bodyWeight": 400,
      "displaySize": 29,
      "bodySize": 13.5,
      "displayTracking": -0.4,
      "displayLine": 1.22,
      "bodyLine": 1.55,
      "labelTracking": 1,
      "labelCase": "upper"
    },
    "layout": {
      "structure": "stat-list",
      "header": "compact",
      "list": "card",
      "button": "rect",
      "progress": "count",
      "photo": "square",
      "density": "tight",
      "radius": 10,
      "hairline": 1,
      "shadow": "hair",
      "edge": 18
    },
    "photo": {
      "heroTags": "exam,daylight",
      "lock": 191
    },
    "avoid": "일러스트를 넣지 않는다. 숫자와 표로만.",
    "rationale": "산타 — 점수와 진단 데이터가 화면의 주인공. 숫자가 크고 나머지는 조밀하다."
  },
  {
    "id": "malhaeboka",
    "name": "말해보카",
    "nameEn": "MalhaeVoca",
    "reference": "말해보카 — 흰 지면 위에 라벤더 알약(pill) 행과 보라 필 버튼. 캐릭터가 앞에 서고, 출석 점·카운트 배지 같은 작은 장치가 목록을 채운다. 하늘·분홍 파스텔 포인트.",
    "idea": "지면은 희게 비우고, 만지는 것마다 라벤더 알약으로 말랑하게 감싼다.",
    "rationale": "말해보카 — 흰 바탕에 보라는 필 버튼과 배지에만. 목록 행은 라벤더 인셋 알약, 진행은 출석 점. 마스코트가 화면의 초점.",
    "avoid": "보라를 지면에 칠하지 않는다(지면은 흰색). 알약 밖 그림자 남발 금지. 파스텔 포인트는 배지·배너에만.",
    "colors": {
      "canvas": "#FFFFFF",
      "surface": "#FFFFFF",
      "ink": "#241A4A",
      "textSecondary": "#453B72",
      "muted": "#635A8F",
      "line": "#E0D9F0",
      "primary": "#7150F0",
      "primaryDark": "#4C34C2",
      "primarySoft": "#EDE7FE",
      "accent": "#F06EAC",
      "onPrimary": "#FFFFFF",
      "success": "#2E9560",
      "warning": "#A8720E",
      "danger": "#D14A6B",
      "backdrop": "#F2EEFB",
      "accentSoft": "#FBE7F1",
      "successSoft": "#E3F2EA",
      "warningSoft": "#F6F0DE",
      "dangerSoft": "#F8E4EC"
    },
    "type": {
      "display": "Gowun Dodum",
      "body": "Pretendard",
      "displayWeight": 400,
      "bodyWeight": 500,
      "displaySize": 30,
      "bodySize": 15,
      "displayTracking": -0.4,
      "displayLine": 1.26,
      "bodyLine": 1.55,
      "labelTracking": 0.4,
      "labelCase": "normal"
    },
    "layout": {
      "structure": "focus-list",
      "header": "stacked",
      "list": "inset",
      "button": "pill",
      "progress": "dots",
      "photo": "rounded",
      "density": "open",
      "radius": 18,
      "hairline": 1,
      "shadow": "soft",
      "edge": 20
    },
    "photo": {
      "heroTags": "study,desk",
      "lock": 197
    }
  }
];

export const DEFAULT_THEME_ID = 'duolingo';

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
