// 에뮬레이터에 표시할 화면 목록 및 메타데이터 레지스트리
export type ScreenCategory = '기존' | '신규' | '수정';

export interface ScreenMeta {
  id: string;
  label: string;
  category: ScreenCategory;
  description: string;
  devNotes: string;
  designNotes: string;
  sourceAFile?: string;
  sourceBRef?: string;
}

export const SCREEN_REGISTRY: ScreenMeta[] = [
  {
    id: 'home',
    label: '1. 나의 코스',
    category: '수정',
    description: '학습자가 앱 진입 시 처음 만나는 화면. 1과 전체 차시 목록과 진도를 한눈에 보여주며, 현재 학습 가능한 차시로 빠르게 진입할 수 있도록 유도한다.',
    devNotes: '참고 파일: src/screens/home/Home.tsx (Source A)\n- SESSIONS 배열로 차시 카드 렌더링\n- sessionProgress() 함수로 각 차시 진행률 계산\n- unlocked 조건: 현재는 1차시만 열림 (서버 API 연동 후 동적 처리 예정)\n- BottomNav 공통 컴포넌트 사용',
    designNotes: '브랜드 컬러: --teal #00a8a6\n카드 모서리: borderRadius 16\n영웅 섹션 배경: tealSoft (#ddfbfa)\n그림자: shadow.card 토큰 사용\n하단 네비: 높이 56px, 상단 1px 보더',
    sourceAFile: 'src/screens/home/Home.tsx',
    sourceBRef: 'HomeScreen',
  },
  {
    id: 'mission',
    label: '2. 학습 미션',
    category: '신규',
    description: '차시 학습 시작 전 미션과 목표를 명확하게 인지시키는 신규 도입 화면. 학습자가 이번 차시에서 배울 내용과 산출물을 미리 확인하고 동기를 갖고 시작하도록 돕는다.',
    devNotes: '참고 파일: Source A에는 해당 화면 없음 (신규 구현)\n- sessionId prop으로 차시별 미션 텍스트 동적 표시\n- SESSION1.mission 데이터 참조\n- subTitles.ko / subTitles.vi로 다국어 처리\n- LangContext useLang() 훅으로 언어 전환',
    designNotes: '히어로 배너: tealSoft 배경, 보더 #b3f0ef\n미션 텍스트: fontSize 17, fontWeight 700, 최대 2줄\n불릿 리스트: teal 색 원형 도트 + 텍스트\n학습 시작 CTA: teal 배경, borderRadius 16',
    sourceAFile: undefined,
    sourceBRef: 'MissionStage',
  },
  {
    id: 'mission-tutor',
    label: '2-1. 학습 미션(튜터)',
    category: '신규',
    description: '차시 학습 시작 전 미션과 목표를 명확하게 인지시키는 신규 도입 화면. 학습자가 이번 차시에서 배울 내용과 산출물을 미리 확인하고 동기를 갖고 시작하도록 돕는다.',
    devNotes: '참고 파일: Source A에는 해당 화면 없음 (신규 구현)\n- sessionId prop으로 차시별 미션 텍스트 동적 표시\n- SESSION1.mission 데이터 참조\n- subTitles.ko / subTitles.vi로 다국어 처리\n- LangContext useLang() 훅으로 언어 전환',
    designNotes: '히어로 배너: tealSoft 배경, 보더 #b3f0ef\n미션 텍스트: fontSize 17, fontWeight 700, 최대 2줄\n불릿 리스트: teal 색 원형 도트 + 텍스트\n학습 시작 CTA: teal 배경, borderRadius 16',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorStage',
  },
  {
    id: 'mission-tutor-prev',
    label: '2-2. 학습 미션(튜터) - 이전 차시',
    category: '신규',
    description: '이전 차시 학습 내용을 포함한 미션 안내 화면. AI 튜터가 이번 차시 학습 내용과 함께 이전 차시 복습 퀴즈가 있음을 안내한다.',
    devNotes: '참고 파일: Source A에는 해당 화면 없음 (신규 구현)\n- MissionTutorStage 복사본\n- 음원: tutor_mission_prev.wav\n- 말풍선 3줄\n- "다음" 버튼 → quick-review 이동',
    designNotes: '히어로 배너: tealSoft 배경, 보더 #b3f0ef\n미션 텍스트: fontSize 17, fontWeight 700, 최대 2줄\n불릿 리스트: teal 색 원형 도트 + 텍스트\n학습 시작 CTA: teal 배경, borderRadius 16',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorPrevStage',
  },
  {
    id: 'mission-tutor-prev-vi',
    label: '2-2. 학습 미션(튜터) - 이전 차시(베트남)',
    category: '신규',
    description: '이전 차시 학습 내용을 포함한 미션 안내 화면. AI 튜터 음원만 재생(말풍선 없음).',
    devNotes: '- MissionTutorPrevStage 복사본\n- 음원: tutor_mission_prev_vi.wav\n- 말풍선 없음\n- "다음" 버튼 → quick-review 이동',
    designNotes: 'MissionTutorPrevStage와 동일',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorPrevViStage',
  },
  {
    id: 'quick-review',
    label: '3. 퀵리뷰',
    category: '신규',
    description: '이전 학습(차시 또는 레슨)에서 학습한 내용에 대한 확인을 통해 이전 학습을 기억하고 있는지 확인하는 템플릿. 문항 카드를 순서대로 확인하며 "기억나요" / "기억이 안 나요"로 응답하고, 전체 완료 후 다음 차시로 진행한다.',
    devNotes: '참고: C:\\dev\\kchao-lesson1-main 2차시 퀵리뷰\n- MOCK_QUICK_REVIEW 데이터 사용 (ADMIN 연동 전 목업)\n- 문항 수: MIN 1 ~ MAX 10\n- 문항 진행: 1번부터 순서대로 잠금 해제\n- 완료 조건: 모든 문항에 응답 완료\n- props: onNext / onBack / data(optional)',
    designNotes: '상단 배지: tealSoft 배경, "퀵 리뷰" 텍스트\n활성 카드: teal 보더 1.5px, 정답 박스(tealSoft)\n잠긴 카드: line 보더, muted 텍스트\n기억나요 버튼: teal 배경\n기억이 안 나요: 테두리 버튼\n하단: 전체 완료 시 다음 차시 버튼 활성화',
    sourceAFile: undefined,
    sourceBRef: 'QuickReviewStage',
  },
   {
    id: 'intro',
    label: '4. 학습 소개(단어)',
    category: '신규',
    description: '차시 핵심 어휘 학습 시작 전 학습 내용을 간단히 안내하는 인트로 화면. 오늘 배울 단어와 학습 성과를 미리 보여주어 학습 동기를 높인다.',
    devNotes: '참고: Source A act31 PreviewIntro4 (src/screens/activity/preview/PreviewIntro4.tsx)\n- SESSION1.intro 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- ActivityLayout 패턴: 프로그레스바 + X 버튼',
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n아이콘: tealSoft 원형(80px), 이모지 36px\n타이틀: 22px bold, center\n학습 성과 카드: #F0FAFA 배경, teal 체크 원형 아이콘',
    sourceAFile: 'src/screens/activity/preview/PreviewIntro4.tsx',
    sourceBRef: 'IntroStage',
  },
  {
    id: 'intro-tutor',
    label: '4-1. 학습 소개(단어-음원)',
    category: '신규',
    description: '차시 핵심 어휘 학습 시작 전 학습 내용을 간단히 안내하는 인트로 화면. 오늘 배울 단어와 학습 성과를 미리 보여주어 학습 동기를 높인다.',
    devNotes: '참고: Source A act31 PreviewIntro4 (src/screens/activity/preview/PreviewIntro4.tsx)\n- SESSION1.intro 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- AI 튜터 오버레이: 진입 시 dim + 썸네일 + 말풍선 + 음원 자동 재생',
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n아이콘: tealSoft 원형(80px), 이모지 36px\n타이틀: 22px bold, center\n학습 성과 카드: #F0FAFA 배경, teal 체크 원형 아이콘',
    sourceAFile: 'src/screens/activity/preview/PreviewIntro4.tsx',
    sourceBRef: 'IntroTutorStage',
  },
  {
    id: 'vocab-wordbook',
    label: '5. 오늘의 단어장',
    category: '신규',
    description: '한국어 단어, 베트남어 번역, 음원 등을 통해 단어를 학습하는 화면. 전체/한국어/베트남어 보기 탭 모드가 제공되며, 음성 배속 재생 조절 및 단어 발음하기 평가 기능이 포함되어 있다.',
    devNotes: '참고: Source B 오늘의 단어 (App.jsx), Source A 단어 발음 평가 (WordPronunciation1.tsx)\n- SESSION1.context.words 데이터 바인딩\n- 재생 속도(0.5x, 1.0x, 1.5x) 음원 재생 로직 포함',
    designNotes: '탭: selected 시 teal 보더 및 텍스트 적용\n단어 리스트: 15개 단어 로우 목록 렌더링\n하단 버튼: 단어 발음하기(Teal 배경) 및 바로 문제 풀기(테두리 버튼)',
    sourceAFile: 'src/screens/activity/word/WordPronunciation1.tsx',
    sourceBRef: 'vocabWordbook',
  },
  // {
  //   id: 'vocab-wordbook-voice',
  //   label: '5-1. 오늘의 단어장(음성)',
  //   category: '신규',
  //   description: '한국어 단어, 베트남어 번역, 음원 등을 통해 단어를 학습하는 화면. 전체/한국어/베트남어 보기 탭 모드가 제공되며, 음성 배속 재생 조절 및 단어 발음하기 평가 기능이 포함되어 있다.',
  //   devNotes: '참고: Source B 오늘의 단어 (App.jsx), Source A 단어 발음 평가 (WordPronunciation1.tsx)\n- SESSION1.context.words 데이터 바인딩\n- 재생 속도(0.5x, 1.0x, 1.5x) 음원 재생 로직 포함',
  //   designNotes: '탭: selected 시 teal 보더 및 텍스트 적용\n단어 리스트: 15개 단어 로우 목록 렌더링\n하단 버튼: 단어 발음하기(Teal 배경) 및 바로 문제 풀기(테두리 버튼)',
  //   sourceAFile: 'src/screens/activity/word/WordPronunciation1.tsx',
  //   sourceBRef: 'VocabWordbookVoiceStage',
  // },
  {
    id: 'word-build',
    label: '6. 단어 만들기',
    category: '신규',
    description: '음원을 듣고 제시된 글자 카드를 순서대로 선택하여 단어를 완성하는 활동. 정오답 피드백 모달, 재생 속도 선택, 힌트, 키보드 입력 모드 제공.',
    devNotes: '참고: Source A WordLetterScramble5 (src/screens/activity/word/WordLetterScramble5.tsx)\n- SESSION1.wordBuildQuiz 데이터 참조 (5문항)\n- 음절 단위 타일\n- 재생 속도: 0.5x / 1.0x / 1.5x\n- FAIL_MAX=2: 2회 오답 시 정답 공개\n- 키보드 모드: TextInput으로 직접 입력',
    designNotes: '오디오 카드: teal 보더, 스피커 버튼(48px 원형) + 답 슬롯\n타일: 48×48px, 선택 시 teal 보더+배경\n피드백 모달: bottom sheet\n힌트: amber 색상',
    sourceAFile: 'src/screens/activity/word/WordLetterScramble5.tsx',
    sourceBRef: 'WordBuildStage',
  },
  {
    id: 'bridge-vocab-grammar',
    label: '7. 브릿지 — 어휘 → 문법',
    category: '신규',
    description: '단어 액티비티 완료 후 문법 액티비티 진입 직전에 노출되는 맥락 연결 전환 화면 (A형). 직전에 학습한 어휘를 문법 예문의 핵심 요소로 재활용하여 단어→문법 학습 사이의 단절을 방지한다. Spotlight Shift + Bridge Quest 패턴 결합.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_VOCAB_GRAMMAR (lessonData.ts)',
      '- bridgeType: "vocab-to-grammar"',
      '- learnedChips: 어휘 칩 (ko + vi 양국어 표시, teal 보더)',
      '- 이식 시: learnedChips → ADMIN API 직전 단어 액티비티 완료 어휘 목록으로 동적 주입',
      '',
      '■ 칩 스타일: VocabChip — teal 보더, #F0FAFA 배경, ko(700) + vi(muted) 2줄',
      '',
      '■ 애니메이션 (5단계 순차): flowOpacity → chipsOpacity → highlightOpacity → suffixOpacity → ctaOpacity',
      '- useNativeDriver: Platform.OS !== "web" 분기 (react-native-web 호환)',
      '',
      '■ 이식 시 주요 변경사항',
      '1. <View style={s.screen}> → <ActivityLayout ...> 교체',
      '2. learnedChips → ADMIN API 응답으로 동적 주입',
      '3. onPressConfirm → 다음 문법 액티비티 네비게이션',
    ].join('\n'),
    designNotes: [
      '■ 레이아웃',
      '- 방향 배지: 📝 어휘 → 문법 (teal 보더 캡슐)',
      '- 브릿지 메시지: 20px bold center',
      '- 어휘 칩: teal 보더, #F0FAFA bg, ko+vi 2줄',
      '- 구분선: line + 안내 텍스트',
      '- 문장 연출: 고정 prefix(muted) + 하이라이트(teal) + suffix(ink)',
      '- 완성 문장 박스: #F0FAFA bg, ko+vi 2줄',
      '- 다음 활동 배지: tealSoft bg, teal text',
      '- 하단 CTA: teal 배경',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'grammar-detail',
    label: '8. 학습 상세 소개',
    category: '신규',
    description: '문법과 표현 학습을 위한 상세 소개 화면. 문법 규칙 배지·타이틀·설명, 유튜브 스타일 영상 썸네일(탭 시 전체화면 재생), 2열 규칙 표, 받침 쌍 시각화가 포함된 보충 설명을 제공한다.',
    devNotes: "참고: Source B 문법과 표현 1 (C:\\dev\\kchao-lesson1-main\\src\\lessonData.js)\n- SESSION1.grammar 데이터 참조 (ruleTable, supplement 포함)\n- 영상: assets/M_1_L1_1080p.mp4 (require로 로드)\n- 전체화면 Modal: Platform.OS === 'web'에서 React.createElement('video', ...) 사용\n- 하단 고정: 다음 버튼",
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n영상 썸네일: aspectRatio 16/9, 반투명 오버레이 + 재생 버튼\n규칙 표: 2열 flex, tealSoft 헤더\n보충 설명: tealSoft 배경 블록, 받침 시각화 카드(흰 배경+shadow)\n요약 버튼: teal 배경 flex row',
    sourceAFile: undefined,
    sourceBRef: 'GrammarDetailStage',
  },
  {
    id: 'sentence-build',
    label: '9. 문장 만들기 1',
    category: '신규',
    description: '음원을 듣고 제시된 단어 카드를 순서대로 선택하여 문장을 완성하는 활동. 베트남어 지문을 보고 해당하는 한국어 문장을 단어 단위 타일로 조합한다.',
    devNotes: '참고: 단어 만들기(WordBuildStage)와 동일한 구조\n- SESSION1.sentenceBuildQuiz 데이터 참조 (5문항)\n- 단어 단위 타일\n- FAIL_MAX=2: 2회 오답 시 정답 공개\n- 키보드 모드, 보기 선택 모드 제공',
    designNotes: '오디오 카드: teal 보더, 스피커 버튼(48px) + 답 영역(dashed)\n단어 타일: capsule 형태, #1A2B3C border\n하단: 확인(flex) + 💡(52px) + 키보드/보기선택 보조 버튼',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage',
  },
  {
    id: 'sentence-build-2',
    label: '10. 문장 만들기 2',
    category: '신규',
    description: '베트남어 문장을 보고 해당하는 한국어 문장을 단어 카드로 조합하는 활동. 오디오 없이 지문 카드를 직접 읽고 해석한다.',
    devNotes: '참고: 문장 만들기 1(SentenceBuildStage)과 동일한 데이터(SESSION1.sentenceBuildQuiz) 사용\n- 오디오 없음, 베트남어 지문 카드 표시\n- 답 영역: 언더라인 스타일\n- 키보드 모드 제공\n- FAIL_MAX=2',
    designNotes: '지문 카드: teal 보더(1.5px), borderRadius 16, 문장 18px bold center\n답 영역: teal 언더라인(2px), 선택 단어 teal pill\n타일: capsule 형태, #1A2B3C border\n하단: 확인(flex) + 💡(52px) + 키보드 사용하기',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage2',
  },
  {
    id: 'culture',
    label: '11. 문화',
    category: '신규',
    description: '별도 오프라인으로 제공되는 교재에서 확인 가능한 한국 문화 정보를 앱에서도 확인할 수 있는 화면. 히어로 이미지/영상, 교재 연계 콘텐츠 카드(번호별 항목 포함)로 구성된다.',
    devNotes: 'MOCK_CULTURE_ACTIVITY 데이터 사용 (ADMIN 연동 전 목업)\n- activityNo / activityQuestionNo 구조로 Source A 이식 기준 준수\n- heroMedia: type(image|video) + uri(ADMIN 등록값, 미등록 시 플레이스홀더)\n- contents[].subItems: 교재 번호별 세부 항목 (선택적)\n- 스크롤 끝까지 읽으면 확인 버튼 활성화\n- props: onPressConfirm / onClose',
    designNotes: '타입 배지: tealSoft 배경, teal 텍스트\n히어로: aspectRatio 16/9, borderRadius 12\n콘텐츠 카드: surface 배경, line 보더, borderRadius 16\n세부 항목 번호: teal 배경 32×32 badge\n하단 버튼: 스크롤 완료 전 비활성(line 배경), 완료 후 teal 배경',
    sourceAFile: undefined,
    sourceBRef: 'CultureStage',
  },
  {
    id: 'bridge-grammar-listening',
    label: '12-A. 브릿지 — 문법 → 듣고 말하기',
    category: '신규',
    description: '문법 액티비티 완료 후 듣고 말하기 활동 진입 직전 노출되는 전환 화면 (B형). 배운 문법 패턴을 실제 음성으로 듣고 따라 말하는 활동으로 자연스럽게 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_LISTENING (lessonData.ts)',
      '- bridgeType: "grammar-to-listening"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
      '- 이식 시: learnedChips → ADMIN API 직전 문법 액티비티의 학습 패턴 목록으로 교체',
      '',
      '■ 칩 스타일: GrammarChip — ink 보더, #F5F5F5 배경, ko만 표시',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: 🎧 문법 → 듣고 말하기',
      '■ 칩: ink 보더 (#F5F5F5 bg), 문법 패턴 텍스트만',
      '■ 나머지 레이아웃은 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'bridge-grammar-speaking',
    label: '12-B. 브릿지 — 문법 → 말하기',
    category: '신규',
    description: '문법 액티비티 완료 후 말하기 활동 진입 직전 노출되는 전환 화면 (C형). 배운 문법 패턴을 스스로 말하는 발화 연습 활동으로 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_SPEAKING (lessonData.ts)',
      '- bridgeType: "grammar-to-speaking"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: 🎤 문법 → 말하기',
      '■ 나머지 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'bridge-grammar-writing',
    label: '12-C. 브릿지 — 문법 → 읽고 쓰기',
    category: '신규',
    description: '문법 액티비티 완료 후 읽고 쓰기 활동 진입 직전 노출되는 전환 화면 (D형). 배운 문법 패턴을 읽고 직접 써보는 활동으로 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_WRITING (lessonData.ts)',
      '- bridgeType: "grammar-to-writing"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: ✏️ 문법 → 읽고 쓰기',
      '■ 나머지 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'video-bridge',
    label: '13. 영상 브릿지',
    category: '신규',
    description: '학습 이동 시 영상으로 학습해야 하는 정보를 알려주는 활동. 전체화면 영상 플레이어로 구성되며, 영상 시청 후 다음 액티비티로 진행한다.',
    devNotes: [
      '■ Source A 참고: act01 / intro_video / PreviewVideo1',
      '  src/screens/activity/preview/PreviewVideo1.tsx',
      '',
      '■ 이식 시 주요 변경사항',
      '1. <View> → <ActivityLayout showHeader={false} useScrollView={false}>',
      '2. LOCAL_VIDEO_ASSET → resolveActivityVideoSource(activity, videoValue)',
      '3. WebVideoPlayer → MissionSummaryVideoPlayer (captionsAvailable, subtitlesText, forcePause, bottomUi)',
      '4. handleConfirm → recordQuestionAttempt + completeActivity + navigateToNextActivityOrLessonComplete',
      '',
      '■ Source A API 데이터 매핑',
      '- getActivityQuestions(activity)[0] → firstQuestion',
      '- getQuestionListItems(question, ["video_subtitles"])[0] → firstItem',
      '- getListItemValueByColumnHeader(firstItem, ["portrait_video"]) → videoValue',
      '- resolveActivityVideoSource(activity, videoValue) → videoSource',
      '',
      '■ 프로토타입 영상 에셋',
      '  assets/video_bridge_intro.mp4 (ADMIN 등록 전 로컬 fallback)',
      '',
      '■ 하단 버튼: "다음" (Source A "학습 시작"에서 변경)',
    ].join('\n'),
    designNotes: [
      '■ 전체 배경: #111111 (다크)',
      '■ 영상 영역: flex:1, objectFit contain',
      '■ 닫기 버튼: 우상단 고정, 반투명 원형 36px',
      '■ 하단 버튼: 흰색 배경(#FFFFFF), teal 텍스트(#00a8a6), borderRadius 14, height 52',
      '■ 이식 시: Source A startButton 스타일(color #2E89FC, pretendard[700]) 참고',
    ].join('\n'),
    sourceAFile: 'src/screens/activity/preview/PreviewVideo1.tsx',
    sourceBRef: undefined,
  },
];

export function getScreen(id: string): ScreenMeta | undefined {
  return SCREEN_REGISTRY.find((s) => s.id === id);
}
