// 에뮬레이터에 표시할 화면 목록 및 메타데이터 레지스트리
export type ScreenCategory = '기존' | '신규' | '수정';

export interface ScreenMeta {
  id: string;
  label: string;
  category: ScreenCategory;
  description: string;
  devNotes: string;
  designNotes: string;
  sourceAFile?: string;
  sourceBRef?: string;
}

export const BASE_SCREEN_REGISTRY: ScreenMeta[] = [
  {
    id: 'home',
    label: '1. 홈 화면 / 코스 안내',
    category: '수정',
    description: '학습자가 앱 진입 시 처음 만나는 화면. 1과 전체 차시 목록과 진도를 한눈에 보여주며, 현재 학습 가능한 차시로 빠르게 진입할 수 있도록 유도한다.',
    devNotes: '참고 파일: src/screens/home/Home.tsx (Source A)\n- SESSIONS 배열로 차시 카드 렌더링\n- sessionProgress() 함수로 각 차시 진행률 계산',
    designNotes: '브랜드 컬러: --teal #00a8a6\n카드 모서리: borderRadius 16',
    sourceAFile: 'src/screens/home/Home.tsx',
    sourceBRef: 'HomeScreen',
  },
  {
    id: 'mission',
    label: '2. 학습 목표',
    category: '신규',
    description: '차시 학습 시작 전 미션과 목표를 명확하게 인지시키는 도입 화면. 이번 차시에서 배울 어휘/문법 목표를 안내한다.',
    devNotes: 'sessionId prop으로 차시별 미션 텍스트 동적 표시',
    designNotes: '히어로 배너: tealSoft 배경, 보더 #b3f0ef',
    sourceAFile: undefined,
    sourceBRef: 'MissionStage',
  },
  {
    id: 'video-bridge',
    label: '16. 문법 강의 영상',
    category: '수정',
    description: '문법 강의 영상(assets/grammer_mov.mp4)을 시청하는 화면. 영상 시청 완료 후 다음으로 이동.',
    devNotes: 'assets/grammer_mov.mp4 전체화면 재생 및 시청 완료 시 다음 활성화',
    designNotes: '다크 테마 비디오 플레이어',
    sourceAFile: 'src/screens/activity/preview/PreviewVideo1.tsx',
    sourceBRef: 'VideoBridgeStage',
  },
  {
    id: 'slide-explain',
    label: '17. 문법 슬라이드식 수업',
    category: '수정',
    description: '슬라이드와 설명 텍스트를 넘기며 문법 규칙을 순서대로 확인하는 활동.',
    devNotes: 'MOCK_SLIDE_EXPLAIN 데이터 참조',
    designNotes: '슬라이드 카드 및 넘기기 인터랙션',
    sourceAFile: undefined,
    sourceBRef: 'SlideExplainStage',
  },
  {
    id: 'sentence-build',
    label: '21. 문법 ACTIVITY 1 (오디오 조합)',
    category: '수정',
    description: '음원을 듣고 제시된 단어 카드를 순서대로 선택하여 문장을 완성하는 활동.',
    devNotes: 'SESSION1.sentenceBuildQuiz 데이터 참조',
    designNotes: '단어 타일 및 조합 슬롯',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage',
  },
  {
    id: 'sentence-build-2',
    label: '22. 문법 ACTIVITY 2 (해석 조합)',
    category: '수정',
    description: '베트남어 문장을 보고 한국어 문장 단어 카드를 조합하는 활동.',
    devNotes: 'SESSION1.sentenceBuildQuiz 데이터 참조',
    designNotes: '지문 카드 및 단어 타일',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage2',
  },
  {
    id: 'quick-review',
    label: '27. 2차시 진입 퀵리뷰',
    category: '수정',
    description: '2차시 진입 시 이전 차시(1차시) 학습 내용에 대한 기억 여부를 확인하는 퀵리뷰 템플릿.',
    devNotes: 'MOCK_QUICK_REVIEW 데이터 사용, 1번 문항부터 순서대로 진행',
    designNotes: '문항 카드, 기억나요 / 기억이 안 나요 버튼',
    sourceAFile: undefined,
    sourceBRef: 'QuickReviewStage',
  },
  // ─── [기타 프로토타입 템플릿 목록] ───────────────────────────
  {
    id: 'mission-tutor',
    label: '2-1. 학습 미션(튜터)',
    category: '신규',
    description: '차시 학습 시작 전 AI 튜터가 미션과 목표를 음성과 말풍선으로 안내하는 화면.',
    devNotes: 'MissionTutorStage',
    designNotes: 'AI 튜터 아바타 및 말풍선',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorStage',
  },
  {
    id: 'mission-tutor-prev',
    label: '2-2. 학습 미션(튜터) - 이전 차시',
    category: '신규',
    description: '이전 차시 학습 내용을 포함한 미션 안내 화면. AI 튜터가 이번 차시 학습 내용과 함께 이전 차시 복습 퀴즈가 있음을 안내한다.',
    devNotes: '참고 파일: Source A에는 해당 화면 없음 (신규 구현)\n- MissionTutorStage 복사본\n- 음원: tutor_mission_prev.wav\n- 말풍선 3줄\n- "다음" 버튼 → quick-review 이동',
    designNotes: '히어로 배너: tealSoft 배경, 보더 #b3f0ef\n미션 텍스트: fontSize 17, fontWeight 700, 최대 2줄\n불릿 리스트: teal 색 원형 도트 + 텍스트\n학습 시작 CTA: teal 배경, borderRadius 16',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorPrevStage',
  },
  {
    id: 'mission-tutor-prev-vi',
    label: '2-2. 학습 미션(튜터) - 이전 차시(베트남)',
    category: '신규',
    description: '이전 차시 학습 내용을 포함한 미션 안내 화면. AI 튜터 음원만 재생(말풍선 없음).',
    devNotes: '- MissionTutorPrevStage 복사본\n- 음원: tutor_mission_prev_vi.wav\n- 말풍선 없음\n- "다음" 버튼 → quick-review 이동',
    designNotes: 'MissionTutorPrevStage와 동일',
    sourceAFile: undefined,
    sourceBRef: 'MissionTutorPrevViStage',
  },
  {
    id: 'quick-review',
    label: '3. 퀵리뷰',
    category: '신규',
    description: '이전 학습(차시 또는 레슨)에서 학습한 내용에 대한 확인을 통해 이전 학습을 기억하고 있는지 확인하는 템플릿. 문항 카드를 순서대로 확인하며 "기억나요" / "기억이 안 나요"로 응답하고, 전체 완료 후 다음 차시로 진행한다.',
    devNotes: '참고: C:\\dev\\kchao-lesson1-main 2차시 퀵리뷰\n- MOCK_QUICK_REVIEW 데이터 사용 (ADMIN 연동 전 목업)\n- 문항 수: MIN 1 ~ MAX 10\n- 문항 진행: 1번부터 순서대로 잠금 해제\n- 완료 조건: 모든 문항에 응답 완료\n- props: onNext / onBack / data(optional)',
    designNotes: '상단 배지: tealSoft 배경, "퀵 리뷰" 텍스트\n활성 카드: teal 보더 1.5px, 정답 박스(tealSoft)\n잠긴 카드: line 보더, muted 텍스트\n기억나요 버튼: teal 배경\n기억이 안 나요: 테두리 버튼\n하단: 전체 완료 시 다음 차시 버튼 활성화',
    sourceAFile: undefined,
    sourceBRef: 'QuickReviewStage',
  },
   {
    id: 'intro',
    label: '4. 학습 소개(단어)',
    category: '신규',
    description: '차시 핵심 어휘 학습 시작 전 학습 내용을 간단히 안내하는 인트로 화면. 오늘 배울 단어와 학습 성과를 미리 보여주어 학습 동기를 높인다.',
    devNotes: '참고: Source A act31 PreviewIntro4 (src/screens/activity/preview/PreviewIntro4.tsx)\n- SESSION1.intro 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- ActivityLayout 패턴: 프로그레스바 + X 버튼',
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n아이콘: tealSoft 원형(80px), 이모지 36px\n타이틀: 22px bold, center\n학습 성과 카드: #F0FAFA 배경, teal 체크 원형 아이콘',
    sourceAFile: 'src/screens/activity/preview/PreviewIntro4.tsx',
    sourceBRef: 'IntroStage',
  },
  {
    id: 'intro-tutor',
    label: '4-1. 학습 소개(문법과 표현)',
    category: '신규',
    description: '차시 문법 학습 시작 전 학습 내용을 간단히 안내하는 인트로 화면. 문법 표현과 학습 성과를 미리 보여주어 학습 동기를 높인다.',
    devNotes: '참고: Source A act31 PreviewIntro4 (src/screens/activity/preview/PreviewIntro4.tsx)\n- SESSION1.intro 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- AI 튜터 오버레이: 진입 시 dim + 썸네일 + 말풍선 + 음원 자동 재생',
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n아이콘: tealSoft 원형(80px), 이모지 36px\n타이틀: 22px bold, center\n학습 성과 카드: #F0FAFA 배경, teal 체크 원형 아이콘',
    sourceAFile: 'src/screens/activity/preview/PreviewIntro4.tsx',
    sourceBRef: 'IntroTutorStage',
  },
  {
    id: 'intro-tutor-2',
    label: '4-1-2. 학습 소개(문법 퀴즈)',
    category: '신규',
    description: '차시 문법 학습의 형성평가(퀴즈) 진입 전 학습 내용을 간단히 안내하는 인트로 화면. 문법 퀴즈와 학습 성과를 미리 보여주어 학습 동기를 높인다.',
    devNotes: '참고: IntroTutorStage 복사본\n- SESSION1.intro 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- AI 튜터 오버레이: 진입 시 dim + 썸네일 + 말풍선 + 음원 자동 재생',
    designNotes: '4-1과 동일 구조 (텍스트만 변경)',
    sourceAFile: 'src/screens/activity/preview/PreviewIntro4.tsx',
    sourceBRef: 'IntroTutorStage',
  },
  {
    id: 'intro-eval',
    label: '4-1-3. 학습 소개(실전 평가)',
    category: '신규',
    description: '차시 학습의 실전평가(형성평가) 진입 전 학습 내용을 간단히 안내하는 인트로 화면. 마이크 아이콘과 발화 평가 안내를 통해 음성 발화 활동으로의 전환을 준비한다.',
    devNotes: '참고: IntroTutorStage 복사본\n- SESSION1.introEvaluation 데이터 참조\n- badge / icon / title / subtitle / achievement 구조\n- AI 튜터 오버레이: 진입 시 dim + 썸네일 + 말풍선 + 음원 자동 재생',
    designNotes: '4-1과 동일 구조 (배지: 실전평가, 아이콘: 🎤, 텍스트 변경)',
    sourceAFile: 'src/screens/IntroEvalStage/index.tsx',
    sourceBRef: 'IntroEvalStage',
  },
  {
    id: 'vocab-wordbook',
    label: '5. 오늘의 단어장',
    category: '신규',
    description: '한국어 단어, 베트남어 번역, 음원 등을 통해 단어를 학습하는 화면. 전체/한국어/베트남어 보기 탭 모드가 제공되며, 음성 배속 재생 조절 및 단어 발음하기 평가 기능이 포함되어 있다.',
    devNotes: '참고: Source B 오늘의 단어 (App.jsx), Source A 단어 발음 평가 (WordPronunciation1.tsx)\n- SESSION1.context.words 데이터 바인딩\n- 재생 속도(0.5x, 1.0x, 1.5x) 음원 재생 로직 포함',
    designNotes: '탭: selected 시 teal 보더 및 텍스트 적용\n단어 리스트: 15개 단어 로우 목록 렌더링\n하단 버튼: 단어 발음하기(Teal 배경) 및 바로 문제 풀기(테두리 버튼)',
    sourceAFile: 'src/screens/activity/word/WordPronunciation1.tsx',
    sourceBRef: 'vocabWordbook',
  },
  {
    id: 'set-wordbook-eval',
    label: '5-2. 단어장과 발음평가',
    category: '신규',
    description: '세트별(1~3) 핵심 어휘(Min 1 ~ Max 5)를 학습하고 발음 평가 및 세트 문제 풀기로 연계되는 템플릿. 1번 세트에는 베트남어 안내 토스트 팝업 및 자동 음원 재생이 지원된다.',
    devNotes: 'SetWordbookEvalStage / 세트 번호(1~3), Set 1 전용 토스트 팝업(word_set_1.mp3), 발음 평가 모달 연동',
    designNotes: '상단 단어장 1/3 배지, 핵심 어휘를 확인해요 타이틀, 토스트 팝업(스피커+닫기), 단어 발음하기 & 세트 문제 풀기 하단 버튼',
    sourceAFile: undefined,
    sourceBRef: 'SetWordbookEvalStage',
  },
  {
    id: 'set-wordbook-eval-2',
    label: '5-2-2. 단어장과 발음평가',
    category: '신규',
    description: '세트 2 핵심 어휘를 학습하고 발음 평가 및 세트 문제 풀기로 연계되는 템플릿. 5-2와 동일한 구조이며 다른 단어 데이터를 포함한다.',
    devNotes: 'SetWordbookEvalStage / 세트 번호(2), Set 2 데이터 사용, 발음 평가 모달 연동',
    designNotes: '5-2와 동일 구조 (setNumber만 2로 변경)',
    sourceAFile: undefined,
    sourceBRef: 'SetWordbookEvalStage',
  },
  {
    id: 'set-wordbook-eval-3',
    label: '5-2-3. 단어장과 발음평가',
    category: '신규',
    description: '세트 3 핵심 어휘를 학습하고 발음 평가 및 세트 문제 풀기로 연계되는 템플릿. 5-2와 동일한 구조이며 다른 단어 데이터를 포함한다.',
    devNotes: 'SetWordbookEvalStage / 세트 번호(3), Set 3 데이터 사용, 발음 평가 모달 연동',
    designNotes: '5-2와 동일 구조 (setNumber만 3으로 변경)',
    sourceAFile: undefined,
    sourceBRef: 'SetWordbookEvalStage',
  },
  // {
  //   id: 'vocab-wordbook-voice',
  //   label: '5-1. 오늘의 단어장(음성)',
  //   category: '신규',
  //   description: '한국어 단어, 베트남어 번역, 음원 등을 통해 단어를 학습하는 화면. 전체/한국어/베트남어 보기 탭 모드가 제공되며, 음성 배속 재생 조절 및 단어 발음하기 평가 기능이 포함되어 있다.',
  //   devNotes: '참고: Source B 오늘의 단어 (App.jsx), Source A 단어 발음 평가 (WordPronunciation1.tsx)\n- SESSION1.context.words 데이터 바인딩\n- 재생 속도(0.5x, 1.0x, 1.5x) 음원 재생 로직 포함',
  //   designNotes: '탭: selected 시 teal 보더 및 텍스트 적용\n단어 리스트: 15개 단어 로우 목록 렌더링\n하단 버튼: 단어 발음하기(Teal 배경) 및 바로 문제 풀기(테두리 버튼)',
  //   sourceAFile: 'src/screens/activity/word/WordPronunciation1.tsx',
  //   sourceBRef: 'VocabWordbookVoiceStage',
  // },
  {
    id: 'word-build',
    label: '6. 단어 만들기',
    category: '신규',
    description: '음원을 듣고 제시된 글자 카드를 순서대로 선택하여 단어를 완성하는 활동. 정오답 피드백 모달, 재생 속도 선택, 힌트, 키보드 입력 모드 제공.',
    devNotes: '참고: Source A WordLetterScramble5 (src/screens/activity/word/WordLetterScramble5.tsx)\n- SESSION1.wordBuildQuiz 데이터 참조 (5문항)\n- 음절 단위 타일\n- 재생 속도: 0.5x / 1.0x / 1.5x\n- FAIL_MAX=2: 2회 오답 시 정답 공개\n- 키보드 모드: TextInput으로 직접 입력',
    designNotes: '오디오 카드: teal 보더, 스피커 버튼(48px 원형) + 답 슬롯\n타일: 48×48px, 선택 시 teal 보더+배경\n피드백 모달: bottom sheet\n힌트: amber 색상',
    sourceAFile: 'src/screens/activity/word/WordLetterScramble5.tsx',
    sourceBRef: 'WordBuildStage',
  },
  {
    id: 'bridge-vocab-grammar',
    label: '7. 브릿지 — 어휘 → 문법',
    category: '신규',
    description: '단어 액티비티 완료 후 문법 액티비티 진입 직전에 노출되는 맥락 연결 전환 화면 (A형). 직전에 학습한 어휘를 문법 예문의 핵심 요소로 재활용하여 단어→문법 학습 사이의 단절을 방지한다. Spotlight Shift + Bridge Quest 패턴 결합.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_VOCAB_GRAMMAR (lessonData.ts)',
      '- bridgeType: "vocab-to-grammar"',
      '- learnedChips: 어휘 칩 (ko + vi 양국어 표시, teal 보더)',
      '- 이식 시: learnedChips → ADMIN API 직전 단어 액티비티 완료 어휘 목록으로 동적 주입',
      '',
      '■ 칩 스타일: VocabChip — teal 보더, #F0FAFA 배경, ko(700) + vi(muted) 2줄',
      '',
      '■ 애니메이션 (5단계 순차): flowOpacity → chipsOpacity → highlightOpacity → suffixOpacity → ctaOpacity',
      '- useNativeDriver: Platform.OS !== "web" 분기 (react-native-web 호환)',
      '',
      '■ 이식 시 주요 변경사항',
      '1. <View style={s.screen}> → <ActivityLayout ...> 교체',
      '2. learnedChips → ADMIN API 응답으로 동적 주입',
      '3. onPressConfirm → 다음 문법 액티비티 네비게이션',
    ].join('\n'),
    designNotes: [
      '■ 레이아웃',
      '- 방향 배지: 📝 어휘 → 문법 (teal 보더 캡슐)',
      '- 브릿지 메시지: 20px bold center',
      '- 어휘 칩: teal 보더, #F0FAFA bg, ko+vi 2줄',
      '- 구분선: line + 안내 텍스트',
      '- 문장 연출: 고정 prefix(muted) + 하이라이트(teal) + suffix(ink)',
      '- 완성 문장 박스: #F0FAFA bg, ko+vi 2줄',
      '- 다음 활동 배지: tealSoft bg, teal text',
      '- 하단 CTA: teal 배경',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'grammar-detail',
    label: '8. 학습 상세 소개',
    category: '신규',
    description: '문법과 표현 학습을 위한 상세 소개 화면. 문법 규칙 배지·타이틀·설명, 유튜브 스타일 영상 썸네일(탭 시 전체화면 재생), 2열 규칙 표, 받침 쌍 시각화가 포함된 보충 설명을 제공한다.',
    devNotes: "참고: Source B 문법과 표현 1 (C:\\dev\\kchao-lesson1-main\\src\\lessonData.js)\n- SESSION1.grammar 데이터 참조 (ruleTable, supplement 포함)\n- 영상: assets/M_1_L1_1080p.mp4 (require로 로드)\n- 전체화면 Modal: Platform.OS === 'web'에서 React.createElement('video', ...) 사용\n- 하단 고정: 다음 버튼",
    designNotes: '배지: tealSoft 배경, teal 텍스트, borderRadius 20\n영상 썸네일: aspectRatio 16/9, 반투명 오버레이 + 재생 버튼\n규칙 표: 2열 flex, tealSoft 헤더\n보충 설명: tealSoft 배경 블록, 받침 시각화 카드(흰 배경+shadow)\n요약 버튼: teal 배경 flex row',
    sourceAFile: undefined,
    sourceBRef: 'GrammarDetailStage',
  },
  {
    id: 'sentence-build',
    label: '9. 문장 만들기 1',
    category: '신규',
    description: '음원을 듣고 제시된 단어 카드를 순서대로 선택하여 문장을 완성하는 활동. 베트남어 지문을 보고 해당하는 한국어 문장을 단어 단위 타일로 조합한다.',
    devNotes: '참고: 단어 만들기(WordBuildStage)와 동일한 구조\n- SESSION1.sentenceBuildQuiz 데이터 참조 (5문항)\n- 단어 단위 타일\n- FAIL_MAX=2: 2회 오답 시 정답 공개\n- 키보드 모드, 보기 선택 모드 제공',
    designNotes: '오디오 카드: teal 보더, 스피커 버튼(48px) + 답 영역(dashed)\n단어 타일: capsule 형태, #1A2B3C border\n하단: 확인(flex) + 💡(52px) + 키보드/보기선택 보조 버튼',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage',
  },
  {
    id: 'sentence-build-2',
    label: '10. 문장 만들기 2',
    category: '신규',
    description: '베트남어 문장을 보고 해당하는 한국어 문장을 단어 카드로 조합하는 활동. 오디오 없이 지문 카드를 직접 읽고 해석한다.',
    devNotes: '참고: 문장 만들기 1(SentenceBuildStage)과 동일한 데이터(SESSION1.sentenceBuildQuiz) 사용\n- 오디오 없음, 베트남어 지문 카드 표시\n- 답 영역: 언더라인 스타일\n- 키보드 모드 제공\n- FAIL_MAX=2',
    designNotes: '지문 카드: teal 보더(1.5px), borderRadius 16, 문장 18px bold center\n답 영역: teal 언더라인(2px), 선택 단어 teal pill\n타일: capsule 형태, #1A2B3C border\n하단: 확인(flex) + 💡(52px) + 키보드 사용하기',
    sourceAFile: undefined,
    sourceBRef: 'SentenceBuildStage2',
  },
  {
    id: 'culture',
    label: '11. 문화',
    category: '신규',
    description: '별도 오프라인으로 제공되는 교재에서 확인 가능한 한국 문화 정보를 앱에서도 확인할 수 있는 화면. 히어로 이미지/영상, 교재 연계 콘텐츠 카드(번호별 항목 포함)로 구성된다.',
    devNotes: 'MOCK_CULTURE_ACTIVITY 데이터 사용 (ADMIN 연동 전 목업)\n- activityNo / activityQuestionNo 구조로 Source A 이식 기준 준수\n- heroMedia: type(image|video) + uri(ADMIN 등록값, 미등록 시 플레이스홀더)\n- contents[].subItems: 교재 번호별 세부 항목 (선택적)\n- 스크롤 끝까지 읽으면 확인 버튼 활성화\n- props: onPressConfirm / onClose',
    designNotes: '타입 배지: tealSoft 배경, teal 텍스트\n히어로: aspectRatio 16/9, borderRadius 12\n콘텐츠 카드: surface 배경, line 보더, borderRadius 16\n세부 항목 번호: teal 배경 32×32 badge\n하단 버튼: 스크롤 완료 전 비활성(line 배경), 완료 후 teal 배경',
    sourceAFile: undefined,
    sourceBRef: 'CultureStage',
  },
  {
    id: 'bridge-grammar-listening',
    label: '12-A. 브릿지 — 문법 → 듣고 말하기',
    category: '신규',
    description: '문법 액티비티 완료 후 듣고 말하기 활동 진입 직전 노출되는 전환 화면 (B형). 배운 문법 패턴을 실제 음성으로 듣고 따라 말하는 활동으로 자연스럽게 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_LISTENING (lessonData.ts)',
      '- bridgeType: "grammar-to-listening"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
      '- 이식 시: learnedChips → ADMIN API 직전 문법 액티비티의 학습 패턴 목록으로 교체',
      '',
      '■ 칩 스타일: GrammarChip — ink 보더, #F5F5F5 배경, ko만 표시',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: 🎧 문법 → 듣고 말하기',
      '■ 칩: ink 보더 (#F5F5F5 bg), 문법 패턴 텍스트만',
      '■ 나머지 레이아웃은 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'bridge-grammar-speaking',
    label: '12-B. 브릿지 — 문법 → 말하기',
    category: '신규',
    description: '문법 액티비티 완료 후 말하기 활동 진입 직전 노출되는 전환 화면 (C형). 배운 문법 패턴을 스스로 말하는 발화 연습 활동으로 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_SPEAKING (lessonData.ts)',
      '- bridgeType: "grammar-to-speaking"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: 🎤 문법 → 말하기',
      '■ 나머지 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'bridge-grammar-writing',
    label: '12-C. 브릿지 — 문법 → 읽고 쓰기',
    category: '신규',
    description: '문법 액티비티 완료 후 읽고 쓰기 활동 진입 직전 노출되는 전환 화면 (D형). 배운 문법 패턴을 읽고 직접 써보는 활동으로 연결한다.',
    devNotes: [
      '■ 데이터: MOCK_BRIDGE_GRAMMAR_WRITING (lessonData.ts)',
      '- bridgeType: "grammar-to-writing"',
      '- learnedChips: 문법 패턴 칩 (ko만 표시, ink 보더)',
    ].join('\n'),
    designNotes: [
      '■ 방향 배지: ✏️ 문법 → 읽고 쓰기',
      '■ 나머지 7번(어휘→문법)과 동일',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'BridgeStage',
  },
  {
    id: 'video-bridge',
    label: '13. 영상 브릿지',
    category: '신규',
    description: '학습 이동 시 영상으로 학습해야 하는 정보를 알려주는 활동. 전체화면 영상 플레이어로 구성되며, 영상 시청 후 다음 액티비티로 진행한다.',
    devNotes: [
      '■ Source A 참고: act01 / intro_video / PreviewVideo1',
      '  src/screens/activity/preview/PreviewVideo1.tsx',
      '',
      '■ 이식 시 주요 변경사항',
      '1. <View> → <ActivityLayout showHeader={false} useScrollView={false}>',
      '2. LOCAL_VIDEO_ASSET → resolveActivityVideoSource(activity, videoValue)',
      '3. WebVideoPlayer → MissionSummaryVideoPlayer (captionsAvailable, subtitlesText, forcePause, bottomUi)',
      '4. handleConfirm → recordQuestionAttempt + completeActivity + navigateToNextActivityOrLessonComplete',
      '',
      '■ Source A API 데이터 매핑',
      '- getActivityQuestions(activity)[0] → firstQuestion',
      '- getQuestionListItems(question, ["video_subtitles"])[0] → firstItem',
      '- getListItemValueByColumnHeader(firstItem, ["portrait_video"]) → videoValue',
      '- resolveActivityVideoSource(activity, videoValue) → videoSource',
      '',
      '■ 프로토타입 영상 에셋',
      '  assets/video_bridge_intro.mp4 (ADMIN 등록 전 로컬 fallback)',
      '',
      '■ 하단 버튼: "다음" (Source A "학습 시작"에서 변경)',
    ].join('\n'),
    designNotes: [
      '■ 전체 배경: #111111 (다크)',
      '■ 영상 영역: flex:1, objectFit contain',
      '■ 닫기 버튼: 우상단 고정, 반투명 원형 36px',
      '■ 하단 버튼: 흰색 배경(#FFFFFF), teal 텍스트(#00a8a6), borderRadius 14, height 52',
      '■ 이식 시: Source A startButton 스타일(color #2E89FC, pretendard[700]) 참고',
    ].join('\n'),
    sourceAFile: 'src/screens/activity/preview/PreviewVideo1.tsx',
    sourceBRef: undefined,
  },
    {
    id: 'slide-explain',
    label: '14. 설명 슬라이드',
    category: '신규',
    description: '관리자(ADMIN)가 등록한 슬라이드(이미지)와 설명 텍스트를 한 쌍(set)으로 구성하여 순서대로 확인하는 활동. 사용자가 직접 슬라이드를 넘기며 학습하고, 마지막 슬라이드 확인 후 다음 단계로 진행할 수 있다.',
    devNotes: '참고: Source B batchim-grammar-steps.html (9단계 콘텐츠 기반 목업)\n- MOCK_SLIDE_EXPLAIN 데이터 참조 (lessonData.ts)\n- SlideItem: { imageUri?: string; text: string } 구조\n- imageUri 미등록 시 플레이스홀더 표시\n- hasSeenLast 상태로 하단 CTA 활성화 제어\n- 이식 시: slides 배열 → ADMIN API 응답으로 교체\n- props: onNext / onBack',
    designNotes: '상단: ActivityHeader (프로그레스바 + X 버튼)\n진행 점: teal 채움(완료) / #e2e8ea(미완료), flex 분할\n이미지 카드: aspectRatio 4/3, borderRadius 16, tealSoft 배경(플레이스홀더)\n캡션 박스: tealSoft 배경, teal 텍스트 bold, borderRadius 14\n이전 버튼: ghost(흰 배경 + line 보더) / 비활성 시 #e2e8ea 보더 + #f8fafb 배경\n넘기기 버튼: ghost(흰 배경 + line 보더) / 비활성 시 동일\n하단 CTA: teal 배경 / 비활성 시 #b9c1c8',
    sourceAFile: undefined,
    sourceBRef: 'SlideExplainStage',
  },
  {
    id: 'speaking-detail',
    label: '15. 말하기 상세 소개',
    category: '신규',
    description: '말하기 활동 진입 전 대화 맥락, 대화문 롤플레잉, 핵심 표현/문화 팁, 교체 연습 패턴을 종합적으로 안내하는 화면. 화자별 말풍선과 오디오 미리듣기, 다국어 번역, 교체 슬롯 카드로 구성된다.',
    devNotes: [
      '■ 데이터: MOCK_SPEAKING_EXPLAIN (lessonData.ts)',
      '- 교재 『ULIS Genie K 한국어 초급 1』 p.7 (말하기 구성), p.24 (말하기 1) 기준',
      '- dialogue: 화자(speaker), 한국어/베트남어 텍스트, 사용자 여부(isUserSpeaker)',
      '- keyTips: 핵심 표현(어느 나라 사람이에요?) 및 호칭(씨) 팁',
      '- drill: 교체 연습 아이템 목록 (이름, 국적, 국기)',
      '- 전체 듣기 및 개별 문장 음성 피드백 인터랙션 포함',
      '- props: onNext / onBack / data(optional)',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 50% + X 버튼)',
      '■ 배지: tealSoft 배경, teal 텍스트 ("말하기 1")',
      '■ 상황 카드: canvas 배경, line 보더, 🤝 아이콘 + 맥락 요약',
      '■ 대화문 프리뷰: 좌(상대방-흰색 말풍선)/우(본인-tealSoft 말풍선) 분리, 음성 스피커 버튼',
      '■ 핵심 표현 팁: 백색 카드 그리드, teal 타이틀 + 다국어 해설',
      '■ 교체 연습: tealSoft 배경 컨테이너 + 화이트 카드(국기, 이름, 국적 알약 배지)',
      '■ 하단 CTA: teal 배경 ("말하기 연습 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'SpeakingDetailStage',
  },
  {
    id: 'read-write-detail',
    label: '16. 읽고 쓰기 상세 소개',
    category: '신규',
    description: '읽고 쓰기 활동 진입 전 읽기 전 유추 스키마 활성화, 읽기 체크 포인트 가이드, 읽기 후 4단계 작문 프레임워크를 제공하는 화면. 대표 인물 프로필, 생각 칩, 정보 탐색 체크리스트, 단계별 작문 카드로 구성된다.',
    devNotes: [
      '■ 데이터: MOCK_READ_WRITE_EXPLAIN (lessonData.ts)',
      '- 교재 『ULIS Genie K 한국어 초급 1』 p.8 (읽고 쓰기 구성), p.31 (읽고 쓰기 1) 기준',
      '- preReading: 본문 등장인물(세나) 및 사전 유추 생각 질문 칩',
      '- readingPoints: 글에서 파악해야 할 3대 정보(이름, 국적, 직업)',
      '- writingFramework: 4단계 작문 구조(인사 → 이름 → 국적/직업 → 끝인사) 및 슬롯 작성 팁',
      '- props: onNext / onBack / data(optional)',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 65% + X 버튼)',
      '■ 배지: tealSoft 배경, teal 텍스트 ("읽고 쓰기")',
      '■ 유추 카드: #F0FAFA 배경, 🔍 아이콘, 세나 캐릭터 프로필 박스 + 💭 생각 칩',
      '■ 읽기 포인트: 번호 원형 배지(teal bg) + 확인 정보 질문 카드',
      '■ 글쓰기 프레임워크: Step 1~4 단계별 블록 카드, 탭 선택 시 teal 하이라이트',
      '■ 하단 CTA: teal 배경 ("읽고 쓰기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'ReadWriteDetailStage',
  },
  {
    id: 'listen-speak-detail',
    label: '17. 듣고 말하기 상세 소개',
    category: '신규',
    description: '듣고 말하기 활동 진입 전 대화 상황 및 등장인물 프리뷰, 청취 집중 미션 안내, 듣기 후 3대 질문-응답 발화 미션을 예고하는 화면. 인물 프로필 카드, 오디오 트랙 안내 배지, 청취 포인트, 질문별 예시 답변 카드로 구성된다.',
    devNotes: [
      '■ 데이터: MOCK_LISTEN_SPEAK_EXPLAIN (lessonData.ts)',
      '- 교재 『ULIS Genie K 한국어 초급 1』 p.9 (듣고 말하기 구성), p.32 (듣고 말하기 1) 기준',
      '- situation: 대화 상황 설명 및 등장인물(민호, 유진) 프로필',
      '- audioTrack: 오디오 트랙명(Tr. 1) 및 길이 정보',
      '- listeningMission: 청취 집중 2대 미션 (이름 매칭, 국적 파악)',
      '- speakingPreview: 3가지 질문-답변 발화 패턴 예고 (인사, 이름, 국적)',
      '- props: onNext / onBack / data(optional)',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 80% + X 버튼)',
      '■ 배지: tealSoft 배경, teal 텍스트 ("듣고 말하기")',
      '■ 상황 카드: #F8FAFC 배경, 🎧 아이콘, 민호/유진 프로필 카드(아바타 + 역할 뱃지)',
      '■ 청취 미션: Tr.1 오디오 배지(teal bg) + 2대 미션 포인트 카드',
      '■ 말하기 발화 예고: Q1~Q3 질문 카드, 탭 시 활성화 + 💬 대답 예시 박스',
      '■ 하단 CTA: teal 배경 ("듣고 말하기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'ListenSpeakDetailStage',
  },
  {
    id: 'speaking-detail-easy',
    label: '15-1. 말하기 상세 소개(초급)',
    category: '신규',
    description: '초급 1 학습자를 위한 말하기 설명 화면. 텍스트 분량을 최소화하고 큼직한 2턴 캐릭터 말풍선과 직관적인 국기/인물 교체 카드로 구성되어 인지 부하 없이 쉽게 학습을 시작할 수 있다.',
    devNotes: [
      '■ 데이터: MOCK_SPEAKING_EASY (lessonData.ts)',
      '- dialoguePairs: 핵심 2턴 대화문 (흐엉 👩 & 민호 👨)',
      '- substitutionDrill: 🇨🇦 로빈, 🇨🇳 팅팅 탭 선택형 직관적 교체 카드',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 50% + X 버튼)',
      '■ 대화 박스: #F8FAFC bg, 큼직한 아바타 + 🔊 음성 피드백 말풍선',
      '■ 원포인트 배너: #FFFBEB bg, 💡 "어느 나라 사람이에요?" 핵심 표현',
      '■ 교체 카드: 탭 선택 시 teal 하이라이트 + 큼직한 국기 이모지',
      '■ 하단 CTA: teal 배경 ("말하기 연습 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'SpeakingDetailEasyStage',
  },
  {
    id: 'read-write-detail-easy',
    label: '16-1. 읽고 쓰기 상세 소개(초급)',
    category: '신규',
    description: '초급 1 학습자를 위한 읽고 쓰기 설명 화면. 세나의 3줄 소개 읽기와 나만의 프로필 카드 완성하기(쓰기)를 2단계 직관적 탭 전환으로 제공한다.',
    devNotes: [
      '■ 데이터: MOCK_READ_WRITE_EASY (lessonData.ts)',
      '- readingCard: 세나 👩‍🏫 3줄 핵심 문장 (안녕하세요? / 한국 사람이에요 / 선생님이에요)',
      '- writingCard: 이름, 국적, 직업 3대 슬롯 빈칸 카드',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 65% + X 버튼)',
      '■ 2단계 전환 탭: 📖 1. 따라 읽기 ↔ ✏️ 2. 직접 쓰기',
      '■ 카드 디자인: #FFFFFF bg + #BFE8E6 보더, 번호 원형 불릿',
      '■ 하단 CTA: teal 배경 ("읽고 쓰기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'ReadWriteDetailEasyStage',
  },
  {
    id: 'listen-speak-detail-easy',
    label: '17-1. 듣고 말하기 상세 소개(초급)',
    category: '신규',
    description: '초급 1 학습자를 위한 듣고 말하기 설명 화면. 1단계 잘 듣기(민호 🇰🇷 & 유진 🇻🇳 인물 매칭)와 2단계 마이크로 따라 말하기(질문-대답 가이드)를 세로 2단 카드로 직관화했다.',
    devNotes: [
      '■ 데이터: MOCK_LISTEN_SPEAK_EASY (lessonData.ts)',
      '- step1Listening: 캐릭터 국기 뱃지 + 오디오 미리듣기 인터랙션',
      '- step2Speaking: 질문 & 내 대답 말풍선 + 🎙️ 마이크 발화 가이드',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 80% + X 버튼)',
      '■ 1단계 카드: 민호/유진 국기 뱃지 + ▶ 미리듣기 버튼',
      '■ 2단계 카드: #FAFCFD bg, 질문(백색) & 내 대답(tealSoft) 말풍선',
      '■ 하단 CTA: teal 배경 ("듣고 말하기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'ListenSpeakDetailEasyStage',
  },
  {
    id: 'speaking-video-demo',
    label: '15-V. 말하기(영상 시연형)',
    category: '신규',
    description: '한국어를 전혀 읽지 못하는 베트남인 초급 학습자를 위한 15초 숏폼 모션 비디오 데모 화면. 텍스트 설명 대신 영상 시연과 3단계 픽토그램 행동 카드(듣기→마이크→말하기)로 말하기 활동 조작법을 직관적으로 안내한다.',
    devNotes: [
      '■ 데이터: MOCK_SPEAKING_VIDEO_DEMO (lessonData.ts)',
      '- videoSrc: assets/video_bridge_intro.mp4 (웹 require 연동)',
      '- actionSteps: 3단계 행동 가이드 (듣기 👂, 마이크 터치 🎙️, 따라 말하기 🗣️)',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 50% + X 버튼)',
      '■ 배지: tealSoft bg ("15초 영상 가이드") + "15s Demo" 배지',
      '■ 영상 플레이어: aspectRatio 16/9, 탭 시 재생 + 자막 하이라이트 박스',
      '■ 3단계 행동 카드: 번호 원형 배지(teal bg) + 픽토그램 아이콘',
      '■ 하단 CTA: teal 배경 ("지금 말하기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'SpeakingVideoDemoStage',
  },
  {
    id: 'speaking-audio-tutor',
    label: '15-A. 말하기(음성 튜터형)',
    category: '신규',
    description: '한국어를 전혀 읽지 못하는 베트남인 초급 학습자를 위한 AI 튜터 보이스 안내 화면. 화면 진입 시 친근한 AI 튜터 아바타가 베트남어 음성으로 활동 목표를 설명하고, 3대 픽토그램 가이드(귀 기울이기→입 열기→국적 말하기)와 다시 듣기(Nghe lại)를 제공한다.',
    devNotes: [
      '■ 데이터: MOCK_SPEAKING_AUDIO_TUTOR (lessonData.ts)',
      '- tutorSpeechVi: 베트남어 안내 대사 및 오디오 파형 인터랙션',
      '- guideChips: 3대 시각 픽토그램 카드',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 50% + X 버튼)',
      '■ 튜터 카드: #F0FAFA bg, 👩‍🏫 아바타 + 오디오 파형 바 + 🔄 다시 듣기 버튼',
      '■ 튜터 말풍선: 베트남어 대사 강조 (14px bold)',
      '■ 픽토그램 가이드: 3개 카드 그리드',
      '■ 하단 CTA: teal 배경 ("말하기 연습 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'SpeakingAudioTutorStage',
  },
  {
    id: 'read-write-visual-slide',
    label: '16-S. 읽고 쓰기(3컷 슬라이드)',
    category: '신규',
    description: '한국어를 전혀 읽지 못하는 베트남인 초급 학습자를 위한 3컷 그림 카드 슬라이드 화면. 텍스트 없이 그림 1장 + 음성 1개로 1컷 만남 -> 2컷 읽기 -> 3컷 쓰기의 3단계를 시각적으로 전달한다.',
    devNotes: [
      '■ 데이터: MOCK_READ_WRITE_VISUAL_SLIDE (lessonData.ts)',
      '- slides: 3컷 그림 카드 (세나 만남 👩‍🏫, 소개글 읽기 📖, 내 카드 채우기 ✏️)',
      '- 컷별 베트남어 음성 청취 버튼 + 이전/다음 슬라이드 탐색',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 65% + X 버튼)',
      '■ 슬라이드 카드: #FFFFFF bg + #BFE8E6 보더, 180px 일러스트 영역 + 음성 버튼',
      '■ 하단 점 인디케이터: 3단계 진행 표시',
      '■ 네비게이션: ‹ 이전 / 다음 컷 ›',
      '■ 하단 CTA: 마지막 슬라이드 도달 시 teal 활성화 ("읽고 쓰기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: 'ReadWriteVisualSlideStage',
  },
  {
    id: 'listen-speak-interactive-try',
    label: '17-T. 듣고 말하기(체험 가이드)',
    category: '신규',
    description: '한국어를 전혀 읽지 못하는 베트남인 초급 학습자를 위한 1회 체험 튜토리얼 화면. 1단계 스피커 버튼 탭(듣기 체험) ➡️ 2단계 마이크 버튼 탭(말하기 체험) ➡️ 튜토리얼 완료 축하 배지 제공 후 본 학습으로 진입한다.',
    devNotes: [
      '■ 데이터: MOCK_LISTEN_SPEAK_INTERACTIVE_TRY (lessonData.ts)',
      '- 3단계 상태 머신: step1 (스피커) -> step2 (마이크) -> completed (성공)',
      '- 버튼 탭 시 펄스 및 음성/녹음 인터랙션 시뮬레이션',
      '- props: onNext / onBack',
    ].join('\n'),
    designNotes: [
      '■ 상단: ActivityHeader (프로그레스바 80% + X 버튼)',
      '■ 1단계 스피커 카드: tealSoft 대형 버튼 + 소리 재생 피드백',
      '■ 2단계 마이크 카드: 앰버/레드 대형 마이크 버튼 + 녹음 피드백',
      '■ 성공 카드: #ECFDF5 bg, 🎉 축하 배지',
      '■ 하단 CTA: 완료 후 teal 활성화 ("듣고 말하기 시작하기 →")',
    ].join('\n'),
    sourceAFile: undefined,
    sourceBRef: undefined,
  },
  {
    id: 'listen-select-1',
    label: '28. 소리 듣고 단어 선택',
    category: '신규',
    description: '음성을 듣고 제시된 단어 선택지 중 정답을 고르는 액티비티. 프로그레스바 헤더 포함.',
    devNotes: 'ListenSelect1 / props: questions, onNext, onBack, currentSetNumber, totalSets / 정답/오답 피드백 모달 포함',
    designNotes: '상단: ActivityHeader 프로그레스바 / 중앙: 질문 + 크기 확대된 음성 버튼(80x80) + 선택지 카드 / MissionStage와 동일한 색상 구조(배경 #FFFFFF)',
    sourceAFile: 'src/screens/ListenSelect1/index.tsx',
    sourceBRef: 'ListenSelect1',
  },
  {
    id: 'word-vn-ko-select-2',
    label: '29. 베트남어 단어 보고 한국어 선택',
    category: '신규',
    description: '베트남어 단어를 보고 해당하는 한국어 선택지를 고르는 액티비티. 프로그레스바 헤더 및 1번 세트 안내 토스트 팝업 포함.',
    devNotes: 'WordVnKoSelect2 / props: questions, onNext, onBack, currentSetNumber, totalSets / 정답/오답 피드백 모달 포함 / Set 1 전용 토스트 팝업',
    designNotes: '상단: ActivityHeader 프로그레스바 / 중앙: 베트남어 단어 카드(토스트 overlaid) + 한국어 선택지 카드(음성버튼) / MissionStage와 동일한 색상 구조(배경 #FFFFFF)',
    sourceAFile: 'src/screens/WordVnKoSelect2/index.tsx',
    sourceBRef: 'WordVnKoSelect2',
  },
  {
    id: 'word-sound-1',
    label: '31. 단어를 보고 음원 선택',
    category: '신규',
    description: '한국어/베트남어 단어를 보고 해당하는 음원 선택지 중 정답을 고르는 액티비티. 프로그레스바 헤더 및 1번 세트 안내 토스트 팝업 포함.',
    devNotes: 'WordSound1 / props: questions, onNext, onBack, currentSetNumber, totalSets / 정답/오답 피드백 모달 포함 / Set 1 전용 토스트 팝업(260825_word_1.mp3)',
    designNotes: '상단: ActivityHeader 프로그레스바 / 중앙: 단어 텍스트 카드(토스트 overlaid) + 2x2 음원 버튼 그리드 / MissionStage와 동일한 색상 구조(배경 #FFFFFF)',
    sourceAFile: 'src/screens/WordSound1/index.tsx',
    sourceBRef: 'WordSound1',
  },
  {
    id: 'word-letter-blank',
    label: '32. 소리를 듣고 빈칸을 채우기',
    category: '신규',
    description: '음원을 듣고 제시된 글자 타일을 순서대로 선택하여 빈칸을 채우는 액티비티. 프로그레스바 헤더 및 1번 세트 안내 토스트 팝업 포함.',
    devNotes: 'WordLetterBlank / props: questions, onNext, onBack, currentSetNumber, totalSets / 정답/오답 피드백 모달 포함 / Set 1 전용 토스트 팝업(260825_word_2.mp3)',
    designNotes: '상단: ActivityHeader 프로그레스바 / 중앙: 음성 버튼 + 빈칸 보드 + 글자 타일 그리드 + 초기화 버튼 / MissionStage와 동일한 색상 구조(배경 #FFFFFF)',
    sourceAFile: 'src/screens/WordLetterBlank/index.tsx',
    sourceBRef: 'WordLetterBlank',
  },
  {
    id: 'set-complete',
    label: '33. 세트 학습 완료 (1/3)',
    category: '신규',
    description: '1 세트 학습 완료 후 노출되는 축하 화면. 체크마크 아이콘과 완료 메시지, 자동 음원 재생 포함.',
    devNotes: 'SetCompleteStage / props: setNumber, totalSets, onNext, onBack / 화면 진입 500ms 후 자동 음원 재생(260825_setcomplete.mp3) / 다국어 지원(한국어/베트남어)',
    designNotes: '상단: ActivityHeader 프로그레스바 / 중앙: 체크마크 아이콘(teal 원형, 80px) + 완료 메시지 3줄 / 하단: 다음→ 버튼(teal soft 배경) / MissionStage와 동일한 색상 구조',
    sourceAFile: 'src/screens/SetCompleteStage/index.tsx',
    sourceBRef: 'SetCompleteStage',
  },
  {
    id: 'set-complete-2',
    label: '34. 세트 학습 완료 (2/3)',
    category: '신규',
    description: '2 세트 학습 완료 후 노출되는 축하 화면. 33번과 동일한 구조.',
    devNotes: 'SetCompleteStage / props: setNumber={2}, totalSets={3}, onNext, onBack',
    designNotes: '33번과 동일 (setNumber만 2로 변경)',
    sourceAFile: 'src/screens/SetCompleteStage/index.tsx',
    sourceBRef: 'SetCompleteStage',
  },
  {
    id: 'set-complete-3',
    label: '35. 세트 학습 완료 (3/3)',
    category: '신규',
    description: '3 세트 학습 완료 후 노출되는 축하 화면. 33번과 동일한 구조.',
    devNotes: 'SetCompleteStage / props: setNumber={3}, totalSets={3}, onNext, onBack',
    designNotes: '33번과 동일 (setNumber만 3으로 변경)',
    sourceAFile: 'src/screens/SetCompleteStage/index.tsx',
    sourceBRef: 'SetCompleteStage',
  },
  {
    id: 'picture-word-2',
    label: '★ 30. 이미지 보고 단어 선택 (PictureWord2)',
    category: '신규',
    description: '이미지를 보고 해당하는 단어 선택지를 고르는 액티비티. 시각적 학습 강화.',
    devNotes: 'PictureWord2 / props: questions, onNext, onBack / 이미지 표시 및 선택지 카드',
    designNotes: '상단: 질문 제목 / 중앙: 이미지 컨테이너 + 단어 선택지 카드 / 하단: 돌아가기',
    sourceAFile: 'src/screens/activity/picture/PictureWord2.tsx',
    sourceBRef: 'PictureWord2',
  },
  {
    id: 'sentence-blank-1',
    label: '11. 문장 빈칸 채우기',
    category: '신규',
    description: '베트남어 지문을 읽고 한국어 문장의 빈칸을 선택지에서 고르는 활동. 문법 이해 강화.',
    devNotes: 'SentenceBlank1 / Source A SentenceBlank1 참고 / props: questions, onNext, onBack, currentSetNumber, totalSets / 단어 선택 기반 답변 / 다국어 지원',
    designNotes: '상단: ActivityHeader 프로그레스바 / 베트남어 지문 카드(#F0FAFA bg, teal border) / 한국어 문장(빈칸 표시___) / 선택지 버튼 / 하단: 확인 버튼 / 피드백 모달',
    sourceAFile: 'src/screens/SentenceBlank1/index.tsx',
    sourceBRef: 'SentenceBlank1',
  },
  {
    id: 'word-blank-1',
    label: '12. 단어 빈칸 채우기',
    category: '신규',
    description: '베트남어 단어를 읽고 한국어 단어의 빈칸을 선택지에서 고르는 활동. 어휘 이해 강화.',
    devNotes: 'WordBlank1 / Source A WordBlank3 참고 / props: questions, onNext, onBack, currentSetNumber, totalSets / 단어 선택 기반 답변 / 다국어 지원',
    designNotes: '상단: ActivityHeader 프로그레스바 / 베트남어 단어 카드 / 한국어 단어(빈칭 표시___) / 선택지 버튼 / 하단: 확인 버튼 / 피드백 모달',
    sourceAFile: 'src/screens/WordBlank1/index.tsx',
    sourceBRef: 'WordBlank1',
  },
  {
    id: 'listen-typing-1',
    label: '13. 음원 듣고 입력하기',
    category: '신규',
    description: '음원을 듣고 베트남어/한국어를 텍스트로 입력하는 활동. 청취 및 입력 능력 강화.',
    devNotes: 'ListenTyping1 / Source A ListenTyping4 참고 / props: questions, onNext, onBack, currentSetNumber, totalSets / 텍스트 입력 기반 답변 / 음원 재생 버튼 / 힌트 표시 가능 / 다국어 지원',
    designNotes: '상단: ActivityHeader 프로그레스바 / 음원 재생 카드(원형 버튼, teal 테두리) / 힌트 카드(옵션) / 텍스트 입력 필드 / 하단: 확인 버튼 / 피드백 모달',
    sourceAFile: 'src/screens/ListenTyping1/index.tsx',
    sourceBRef: 'ListenTyping1',
  },
  {
    id: 'sentence-select-1',
    label: '14. 뜻에 맞는 문장 고르기',
    category: '신규',
    description: '베트남어 문장을 읽고 한국어 문장 선택지 중 뜻에 맞는 것을 고르는 활동. 문장 이해력 강화.',
    devNotes: 'SentenceSelect1 / Source A SentenceBlank1 참고 / props: questions, onNext, onBack, currentSetNumber, totalSets / 문장 선택 기반 답변 (라디오 버튼) / 다국어 지원',
    designNotes: '상단: ActivityHeader 프로그레스바 / 베트남어 지문 카드(#F0FAFA bg, teal border) / 한국어 문장 선택지 (라디오 버튼 + 텍스트) / 하단: 확인 버튼 / 피드백 모달',
    sourceAFile: 'src/screens/SentenceSelect1/index.tsx',
    sourceBRef: 'SentenceSelect1',
  },
  {
    id: 'speaking-eval',
    label: '15. 실전평가 (음성 발화)',
    category: '신규',
    description: '빈칸을 채우고 음성으로 발화하는 형성평가 활동. 4단계(1/4~4/4)로 구성되며 각 단계에서 텍스트 입력 후 마이크로 녹음하는 방식으로 진행된다.',
    devNotes: 'SpeakingEvalStage / props: questions, onNext, onBack, currentSetNumber, totalSets / 여러 단계의 빈칙 채우기 / 마이크 음성 녹음 기능 / 다국어 지원',
    designNotes: '상단: 단계 표시(실전평가 · 1/4 등) / 안내 문장(리스트) / 입력 필드들 / 마이크 버튼(원형, teal) / 하단: 다음/제출 버튼',
    sourceAFile: 'src/screens/SpeakingEvalStage/index.tsx',
    sourceBRef: 'SpeakingEvalStage',
  },
  {
    id: 'learning-report',
    label: '16. 학습 리포트',
    category: '신규',
    description: '1차시 학습 완료 후 전체 학습 성과를 요약하는 최종 리포트. 어휘, 발음평가, 문제 현황 및 AI 피드백을 포함한다.',
    devNotes: 'LearningReportStage / props: data, onNext, onBack / 학습 성과 요약(어휘 수, 발음평가 점수, 확인 문제 점수) / 재학습 섹션(단어, 문법, 음성) / AI 피드백 영역 / 다국어 지원',
    designNotes: '상단: 배지(학습 리포트) + 프로그레스바 / 제목 및 설명 / 요약 카드(3개 항목: 어휘, 발음평가, 확인문제) / 재학습 섹션(3개 항목) / AI 피드백 영역(노란 배경) / 하단: 학습 완료 버튼',
    sourceAFile: 'src/screens/LearningReportStage/index.tsx',
    sourceBRef: 'LearningReportStage',
  },
  {
    id: 'completion-celebration-vocab',
    label: '17-1. 완료 축하 화면(단어)',
    category: '신규',
    description: '단어 학습 완료 시 축하와 격려를 표현하는 화면. 파티클 애니메이션과 함께 "대단해요!" 메시지 표시.',
    devNotes: 'CompletionCelebrationVocabStage / props: title, titleVi, description, descriptionVi, nextButtonText, nextButtonTextVi, onNext, onBack / CSS 파티클 애니메이션(60개 이모지) / 다국어 지원',
    designNotes: '상단: 파티클 애니메이션(🎉✨🎊 이모지) / 아이콘 원형 배경(tealSoft) / 제목("대단해요!") / 설명 텍스트 / 하단: 확인 버튼(teal 배경)',
    sourceAFile: undefined,
    sourceBRef: 'CompletionCelebrationVocabStage',
  },
  {
    id: 'completion-celebration-grammar',
    label: '17-2. 완료 축하 화면(문법)',
    category: '신규',
    description: '문법 학습 완료 시 축하와 격려를 표현하는 화면. 파티클 애니메이션과 함께 "대단해요!" 메시지 표시.',
    devNotes: 'CompletionCelebrationGrammarStage / props: title, titleVi, description, descriptionVi, nextButtonText, nextButtonTextVi, onNext, onBack / CSS 파티클 애니메이션(60개 이모지) / 다국어 지원',
    designNotes: '상단: 파티클 애니메이션(🎉✨🎊 이모지) / 아이콘 원형 배경(tealSoft) / 제목("대단해요!") / 설명 텍스트 / 하단: 확인 버튼(teal 배경)',
    sourceAFile: undefined,
    sourceBRef: 'CompletionCelebrationGrammarStage',
  },
  {
    id: 'completion-celebration-class',
    label: '17-3. 완료 축하 화면(수업)',
    category: '신규',
    description: '수업 전체 완료 시 축하와 격려를 표현하는 화면. 파티클 애니메이션과 함께 "대단해요!" 메시지 표시.',
    devNotes: 'CompletionCelebrationClassStage / props: title, titleVi, description, descriptionVi, nextButtonText, nextButtonTextVi, onNext, onBack / CSS 파티클 애니메이션(60개 이모지) / 다국어 지원',
    designNotes: '상단: 파티클 애니메이션(🎉✨🎊 이모지) / 아이콘 원형 배경(tealSoft) / 제목("대단해요!") / 설명 텍스트 / 하단: 확인 버튼(teal 배경)',
    sourceAFile: undefined,
    sourceBRef: 'CompletionCelebrationClassStage',
  },
];

export const SCREEN_REGISTRY: ScreenMeta[] = [
  ...BASE_SCREEN_REGISTRY,
];

export function getScreen(id: string): ScreenMeta | undefined {
  return SCREEN_REGISTRY.find((s) => s.id === id);
}

